{{- if eq (include "opensearch.enableDisasterRecovery" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "opensearch.fullname" . }}-replication-configuration
  labels:
    name: {{ template "opensearch.fullname" . }}-replication
    component: opensearch-replication
data:
  indicesPattern: {{ .Values.global.disasterRecovery.indicesPattern | quote }}
  remoteCluster: {{ .Values.global.disasterRecovery.remoteCluster | quote }}
{{- end }}