{{- if and (eq (include "opensearch.enableDisasterRecovery" .) "true") .Values.global.disasterRecovery.serviceExport.enabled }}
kind: Service
apiVersion: v1
metadata:
  annotations:
{{ toYaml .Values.opensearch.client.service.annotations | indent 4 }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    role: client
  name: {{ template "opensearch-gke-service-name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: transport
      port: 9300
  selector:
    {{- if .Values.opensearch.client.dedicatedPod.enabled }}
    role: client
    {{- else }}
    role: master
  {{- end }}
  type: {{ .Values.opensearch.client.service.type }}
{{- end }}