{{- if and (eq (include "opensearch.enableDisasterRecovery" .) "true") .Values.global.disasterRecovery.siteManagerEnabled }}
apiVersion: netcracker.com/v3
kind: SiteManager
metadata:
  name: opensearch-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "opensearch.fullname" . }}
    release: {{ .Release.Name }}
spec:
  sitemanager:
    module: "stateful"
    {{- with .Values.global.disasterRecovery.afterServices }}
    after:
      {{- range . }}
      - {{ . }}
      {{- end }}
    {{- else }}
    after: []
    {{- end }}
    before: []
    sequence: ["active", "standby"]
    timeout: {{ .Values.global.disasterRecovery.timeout }}
    parameters:
      serviceEndpoint: "{{ template "disasterRecovery.protocol" . }}://{{ template "opensearch.fullname" . }}-disaster-recovery.{{ .Release.Namespace }}.svc.cluster.local:{{ template "disasterRecovery.port" . }}/sitemanager"
      healthzEndpoint: "{{ template "disasterRecovery.protocol" . }}://{{ template "opensearch.fullname" . }}-disaster-recovery.{{ .Release.Namespace }}.svc.cluster.local:{{ template "disasterRecovery.port" . }}/healthz"
{{- end }}
