kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.service.name }}
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .Values.service.name }}
    spec:
      serviceAccountName: {{ .Values.service.name }}
      {{- if .Values.integrationTests.affinity }}
      affinity:
      {{ .Values.integrationTests.affinity | toJson }}
      {{- end }}
      securityContext:
        {{- include "opensearch-service.globalPodSecurityContext" . | nindent 8 }}
        {{- with .Values.integrationTests.securityContext }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}
      containers:
        - name: {{ .Values.service.name }}
          image: {{ template "integration-tests.image" . }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            {{- if .Values.integrationTests.statusWritingEnabled }}
            - name: STATUS_WRITING_ENABLED
              value: "{{ .Values.integrationTests.statusWritingEnabled }}"
            - name: IS_SHORT_STATUS_MESSAGE
              value: "{{ .Values.integrationTests.isShortStatusMessage }}"
            - name: ONLY_INTEGRATION_TESTS
              value: "true"
            - name: STATUS_CUSTOM_RESOURCE_NAME
              value: {{ .Values.service.name }}
            - name: STATUS_CUSTOM_RESOURCE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- end }}
            - name: OPENSEARCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TAGS
              value: {{ .Values.integrationTests.tags }}
            - name: OPENSEARCH_PROTOCOL
              value: {{ .Values.integrationTests.opensearchProtocol | default "http" }}
            - name: OPENSEARCH_HOST
              value: {{ .Values.integrationTests.opensearchHost | default "opensearch" }}
            - name: OPENSEARCH_PORT
              value: "{{ .Values.integrationTests.opensearchPort | default 9200 }}"
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: opensearch-username
                  name: {{ .Values.service.name }}-secret
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: opensearch-password
                  name: {{ .Values.service.name }}-secret
            - name: OPENSEARCH_MASTER_NODES_NAME
              value: {{ .Values.integrationTests.opensearchMasterNodesName | default "opensearch" }}
            - name: IDENTITY_PROVIDER_URL
              value: "{{ .Values.integrationTests.identityProviderUrl }}"
            - name: IDENTITY_PROVIDER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service.name }}-secret
                  key: idp-registration-token
            - name: IDENTITY_PROVIDER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service.name }}-secret
                  key: idp-username
            - name: IDENTITY_PROVIDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service.name }}-secret
                  key: idp-password
            - name: DBAAS_ADAPTER_TYPE
              value: {{ .Values.integrationTests.dbaasAdapterType | default "opensearch" }}
            - name: OPENSEARCH_DBAAS_ADAPTER_HOST
              value: {{ .Values.integrationTests.opensearchDbaasAdapterHost | default "dbaas-opensearch-adapter" }}
            - name: OPENSEARCH_DBAAS_ADAPTER_PORT
              value: "{{ .Values.integrationTests.opensearchDbaasAdapterPort | default 8080 }}"
            - name: OPENSEARCH_DBAAS_ADAPTER_PROTOCOL
              value: {{ .Values.integrationTests.opensearchDbaasAdapterProtocol | default "http" }}
            - name: OPENSEARCH_DBAAS_ADAPTER_REPOSITORY
              value: {{ .Values.integrationTests.opensearchDbaasAdapterRepository | default "snapshots" }}
            - name: OPENSEARCH_DBAAS_ADAPTER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: dbaas-adapter-username
                  name: {{ .Values.service.name }}-secret
            - name: OPENSEARCH_DBAAS_ADAPTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: dbaas-adapter-password
                  name: {{ .Values.service.name }}-secret
            - name: OPENSEARCH_DBAAS_ADAPTER_API_VERSION
              value: {{ .Values.integrationTests.opensearchDbaasAdapterApiVersion | quote }}
            - name: OPENSEARCH_CURATOR_PROTOCOL
              {{- if .Values.tls.curator.secretName }}
              value: "https"
              {{ else }}
              value: "http"
              {{- end }}
            - name: OPENSEARCH_CURATOR_HOST
              value: {{ .Values.integrationTests.opensearchCuratorHost | default "opensearch-curator" }}
            - name: OPENSEARCH_CURATOR_PORT
              {{- if .Values.tls.curator.secretName }}
              value: "8443"
              {{- else }}
              value: "8080"
              {{- end }}
            - name: OPENSEARCH_CURATOR_USERNAME
              valueFrom:
                secretKeyRef:
                  key: curator-username
                  name: {{ .Values.service.name }}-secret
            - name: OPENSEARCH_CURATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: curator-password
                  name: {{ .Values.service.name }}-secret
            - name: S3_ENABLED
            value: {{ .Values.opensearch.snapshots.s3.enabled | quote }}
            - name: S3_URL
              value: {{ .Values.opensearch.snapshots.s3.url | quote }}
            - name: S3_BUCKET
              value: {{ .Values.opensearch.snapshots.s3.bucket | quote }}
            - name: S3_KEY_ID
              {{- if .Values.opensearch.snapshots.s3.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-s3-secret
                  key: s3-key-id
              {{- end }}
            - name: S3_KEY_SECRET
              {{- if .Values.opensearch.snapshots.s3.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-s3-secret
                  key: s3-key-secret
              {{- end }}
            - name: PROMETHEUS_URL
              value: {{ .Values.integrationTests.prometheusUrl }}
            - name: SLOW_QUERIES_INTERVAL_MINUTES
              value: "{{ .Values.integrationTests.slowQueriesIntervalMinutes }}"
          resources:
            requests:
              memory: {{ default "256Mi" .Values.integrationTests.resources.requests.memory }}
              cpu: {{ default "200m" .Values.integrationTests.resources.requests.cpu }}
            limits:
              memory: {{ default "256Mi" .Values.integrationTests.resources.limits.memory }}
              cpu: {{ default "400m" .Values.integrationTests.resources.limits.cpu }}
          securityContext:
            {{- include "opensearch-service.globalContainerSecurityContext" . | nindent 12 }}
          volumeMounts:
            - name: output
              mountPath: /opt/robot/output
            {{- if .Values.tls.opensearch.secretName }}
            - mountPath: /certs/opensearch/root-ca.pem
              name: opensearch-certs
              subPath: {{ .Values.tls.opensearch.secretCaKey | default "ca.crt" }}
            {{- end }}
            {{- if .Values.tls.curator.secretName }}
            - mountPath: /certs/curator/root-ca.pem
              name: curator-certs
              subPath: "ca.crt"
            {{- end }}
            {{- if .Values.tls.dbaasAdapter.secretName}}
            - mountPath: /certs/dbaas-adapter/ca.crt
              name: dbaas-adapter-certs
              subPath: "ca.crt"
            {{- end }}
          terminationMessagePath: /dev/termination-log
      volumes:
        - name: output
          emptyDir: {}
        {{- if .Values.tls.opensearch.secretName }}
        - name: opensearch-certs
          secret:
            secretName: {{ .Values.tls.opensearch.secretName }}
        {{- end }}
        {{- if .Values.tls.curator.secretName }}
        - name: curator-certs
          secret:
            secretName: {{ .Values.tls.curator.secretName }}
        {{- end }}
        {{- if .Values.tls.dbaasAdapter.secretName }}
        - name: dbaas-adapter-certs
          secret:
            secretName: {{ .Values.tls.dbaasAdapter.secretName }}
        {{- end }}
