{{- if .Values.curator.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    name: {{ template "opensearch.fullname" . }}-curator
    component: opensearch-curator
  name: {{ template "opensearch.fullname" . }}-curator
spec:
  ports:
    - name: opensearch-curator-backup
      port: 8080
      protocol: TCP
  selector:
    name: {{ template "opensearch.fullname" . }}-curator
    component: opensearch-curator
{{- end }}