{{- if .Values.curator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
    name: {{ template "opensearch.fullname" . }}-curator
    component: opensearch-curator
  name: {{ template "opensearch.fullname" . }}-curator-secret
type: Opaque
stringData:
  username: "{{ .Values.curator.username }}"
  password: "{{ .Values.curator.password }}"
{{- end }}