{{- if .Values.curator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    name: {{ template "opensearch.fullname" . }}-curator
    component: opensearch-curator
  name: {{ template "opensearch.fullname" . }}-curator
spec:
  replicas: {{ template "opensearch.replicasForSingleService" . }}
  selector:
    matchLabels:
{{ include "opensearch.labels.selector" . | indent 6 }}
      name: {{ template "opensearch.fullname" . }}-curator
      component: opensearch-curator
  template:
    metadata:
      labels:
{{- with .Values.global.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{- with .Values.curator.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{ include "opensearch.labels.standard" . | indent 8 }}
        name: {{ template "opensearch.fullname" . }}-curator
        component: opensearch-curator
    spec:
      containers:
        - env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: ES_HOST
              value: {{ default (printf "%s-internal:9200" (include "opensearch.fullname" .)) (.Values.global.externalOpensearch.enabled | ternary (printf "%s:%s" (include "external.opensearch-host" .) (include "external.opensearch-port" .)) .Values.curator.opensearchHost) }}
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ template "opensearch.fullname" . }}-secret
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "opensearch.fullname" . }}-secret
            - name: ES_AUTH
              value: "$(ES_USERNAME):$(ES_PASSWORD)"
            - name: TLS_HTTP_ENABLED
              value: "{{ or .Values.global.externalOpensearch.enabled (eq (include "opensearch.tlsEnabled" .) "true") }}"
            - name: TLS_ENABLED
              value: "{{ template "curator.tlsEnabled" . }}"
            - name: SNAPSHOT_REPOSITORY_NAME
              value: {{ .Values.curator.snapshotRepositoryName | default "snapshots" }}
          {{- if .Values.curator.backupSchedule }}
            - name: BACKUP_SCHEDULE
              value: {{ .Values.curator.backupSchedule }}
          {{- end }}
          {{- if .Values.curator.evictionPolicy }}
            - name: EVICTION_POLICY
              value: {{ .Values.curator.evictionPolicy }}
          {{- end }}
          {{- if and .Values.opensearch.snapshots.enabled .Values.opensearch.snapshots.s3.enabled }}
            - name: S3_ENABLED
              value: {{ .Values.opensearch.snapshots.s3.enabled | quote }}
            - name: S3_URL
              value: {{ .Values.opensearch.snapshots.s3.url | quote }}
            - name: S3_BUCKET
              value: {{ .Values.opensearch.snapshots.s3.bucket | quote }}
            - name: S3_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-s3-secret
                  key: s3-key-id
            - name: S3_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-s3-secret
                  key: s3-key-secret
          {{- end }}
            - name: BACKUP_DAEMON_API_CREDENTIALS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-curator-secret
                  key: username
            - name: BACKUP_DAEMON_API_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-curator-secret
                  key: password
          image: {{ template "curator.image" . }}
          imagePullPolicy: {{ .Values.curator.imagePullPolicy | default "Always" | quote }}
          resources:
{{ toYaml .Values.curator.resources | indent 12 }}
          name: {{ template "opensearch.fullname" . }}-curator
          volumeMounts:
            - mountPath: /backup-storage
              name: backup-storage
            {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
            - mountPath: /trusted-certs/root-ca.pem
              name: opensearch-certs
              subPath: {{ template "opensearch.rest-root-ca-path" . }}
            {{- end }}
            {{ if eq (include "curator.tlsEnabled" .) "true" }}
            - mountPath: /tls
              name: certs
            {{- end }}
          ports:
            - protocol: TCP
              containerPort: 8080
        - env:
            - name: CLOUD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ELASTICSEARCH_HOST
              value: {{ default (printf "%s-internal:9200" (include "opensearch.fullname" .)) (.Values.global.externalOpensearch.enabled | ternary (printf "%s:%s" (include "external.opensearch-host" .) (include "external.opensearch-port" .)) .Values.curator.opensearchHost) }}
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ template "opensearch.fullname" . }}-secret
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "opensearch.fullname" . }}-secret
            - name: ES_AUTH
              value: "$(ES_USERNAME):$(ES_PASSWORD)"
            - name: TLS_HTTP_ENABLED
              value: "{{ or .Values.global.externalOpensearch.enabled (eq (include "opensearch.tlsEnabled" .) "true") }}"
            - name: INDICES_CLEANER_SCHEDULER_UNIT
              value: {{ .Values.curator.indicesCleanerSchedulerUnit | default "days" }}
            - name: INDICES_CLEANER_SCHEDULER_UNIT_COUNT
              value: "{{ .Values.curator.indicesCleanerSchedulerUnitCount | default 1 }}"
            - name: INDICES_CLEANER_CONFIGURATION_KEY
              value: {{ .Values.curator.indicesCleanerConfigurationKey | default "patterns_to_delete" }}
          image: {{ template "indices-cleaner.image" . }}
          imagePullPolicy: {{ .Values.curator.imagePullPolicy | default "Always" | quote }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - ps aux | grep "python3 indices_cleaner.py"
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          name: {{ template "opensearch.fullname" . }}-indices-cleaner
          resources:
{{ toYaml .Values.curator.resources | indent 12 }}
          volumeMounts:
            - mountPath: /opt/elasticsearch-indices-cleaner/cleaner.yml
              name: config
              subPath: cleaner.yml
            {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
            - mountPath: /trusted-certs/root-ca.pem
              name: opensearch-certs
              subPath: {{ template "opensearch.rest-root-ca-path" . }}
            {{- end }}
      volumes:
        {{- if or (not .Values.opensearch.snapshots.enabled) .Values.opensearch.snapshots.s3.enabled }}
        - name: backup-storage
          emptyDir: {}
        {{- else }}
        - name: backup-storage
          persistentVolumeClaim:
            claimName: {{ .Values.opensearch.snapshots.persistentVolumeClaim | default (printf "pvc-%s-snapshots" (include "opensearch.fullname" .))  }}
        {{- end }}
        - name: config
          configMap:
            name: {{ template "opensearch.fullname" . }}-indices-cleaner-configuration
            items:
              - path: cleaner.yml
                key: config
        {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
        - name: opensearch-certs
          secret:
            secretName: {{ template "opensearch.rest-cert-secret-name" . }}
        {{- end }}
        {{ if eq (include "curator.tlsEnabled" .) "true" }}
        - name: certs
          secret:
            secretName: {{ template "curator.certSecretName" . }}
        {{- end }}
    {{- with .Values.curator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.curator.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.curator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.curator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
