{{- if .Values.curator.enabled }}
{{- $install := and (eq (include "curator.tlsEnabled" .) "true") ( or .Values.global.tls.generateCerts.enabled (eq (include "curator.certificatesSpecified" .) "true")) }}
{{- $secretName := include "curator.certSecretName" . }}
{{- if and $install (ne (include "certProvider" .) "cert-manager") (not (lookup "v1" "Secret" .Release.Namespace $secretName)) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
data:
{{- if not .Values.global.tls.generateCerts.enabled }}
  tls.crt: {{ .Values.curator.tls.certificates.crt | quote }}
  tls.key: {{ .Values.curator.tls.certificates.key | quote }}
  ca.crt: {{ .Values.curator.tls.certificates.ca | quote }}
{{- else }}
{{ include "curator.generateCerts" . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}