{{- if and .Values.global.rbac.enabled (eq (include "pod-scheduler-enabled" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "opensearch.fullname" . }}-pod-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
rules:
  - verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - pods/binding
{{- end }}
