{{- if and .Values.global.rbac.enabled (eq (include "pod-scheduler-enabled" .) "true") }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
  name: {{ template "opensearch.fullname" . }}-pod-scheduler
roleRef:
  kind: Role
  name: {{ template "opensearch.fullname" . }}-pod-scheduler
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "opensearch.fullname" . }}-pod-scheduler
    namespace: {{ .Release.Namespace }}
{{- end }}
