{{ if and .Values.ENABLE_PRIVILEGED_PSS (eq (include "opensearch.restrictedEnvironment" .) "false") }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "opensearch.fullname" . }}-update-resources
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ template "opensearch.fullname" . }}-update-resources
roleRef:
  kind: Role
  name: {{ template "opensearch.fullname" . }}-update-resources
  apiGroup: rbac.authorization.k8s.io
{{ end }}