{{- if and (eq .Values.global.restrictedEnvironment "true") (eq .Values.INFRA_RESTRICTED_ENVIRONMENT "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opensearch.fullname" . }}-update-resources
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range . }}
  - name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}