{{- if (eq (include "monitoring.enabled" .) "true") }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "opensearch.fullname" . }}-monitoring
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "opensearch.fullname" . }}-monitoring
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "opensearch.fullname" . }}-monitoring
  apiGroup: rbac.authorization.k8s.io
{{- end }}