{{- if  and (eq (include "monitoring.enabled" .) "true") (eq .Values.monitoring.monitoringType "influxdb") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opensearch.fullname" . }}-monitoring-secret
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  sm-db-username: "{{ .Values.monitoring.smDbUsername }}"
  sm-db-password: "{{ .Values.monitoring.smDbPassword }}"
{{- end }}