version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/operator"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "gomod"
    directory: "/dbaas-adapter"
    schedule:
      interval: "weekly"
  
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/integration-tests/docker"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "pip"
    directory: "/monitoring/docker/config"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "pip"
    directory: "/curator/opensearch_indices_cleaner/docker"
    schedule:
      interval: "weekly"
  
  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/docker-opensearch/opensearch-filter-plugin"
    schedule:
      interval: "weekly"
  
  # Helm charts
  - package-ecosystem: "helm"
    directory: "/operator/charts/helm/opensearch-service"
    schedule:
      interval: "weekly"
  
  # Docker images
  - package-ecosystem: "docker"
    directory: "/operator"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/docker-transfer"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/tls-init/docker"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/operator/dev-kit"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/monitoring/docker"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/dbaas-adapter/docker"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/docker-opensearch/docker"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/integration-tests/docker"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/curator/docker/backup-docker"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "docker"
    directory: "/curator/opensearch_indices_cleaner/docker"
    schedule:
      interval: "weekly"
