JOB_NAME: DP.Pub.Sandbox_Orchestrator_v1
SERVER: https://git.netcracker.com
JENKINS_URL: https://cisrvrecn.netcracker.com
REPOSITORY_NAME: PROD.Platform.ElasticStack/opensearch-service
CLOUD_UI_URL: https://dashboard.ci-master.openshift.sdntest.netcracker.com/#/overview?namespace=
CLOUD_NAMESPACE: opensearch-service
# Build Params
LOCATION: ${CI_COMMIT_REF_NAME}
PREFIX: ${PREFIX}
# Deploy Params
ENABLE_DEPLOY: 'true'
DEPLOYER_VERSION: helm_x