linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

run:
  timeout: 10m
  go: '1.18'
  modules-download-mode: readonly