{{- if eq (include "dbaas.enabled" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    name: {{ template "dbaas-adapter.name" . }}
    component: dbaas-opensearch-adapter
  name: {{ template "dbaas-adapter.name" . }}
spec:
  ports:
    - name: {{ template "dbaas-adapter.protocol" . }}
      port: {{ template "dbaas-adapter.port" . }}
      protocol: TCP
  selector:
    name: {{ template "dbaas-adapter.name" . }}
    component: dbaas-opensearch-adapter
{{- end }}