{{- if eq (include "dbaas.enabled" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    name: {{ template "dbaas-adapter.name" . }}
    component: dbaas-opensearch-adapter
  name: {{ template "dbaas-adapter.name" . }}-secret
type: Opaque
stringData:
  username: "{{ .Values.dbaasAdapter.dbaasUsername }}"
  password: "{{ .Values.dbaasAdapter.dbaasPassword }}"
  registration-auth-username: "{{ include "dbaas.registrationUsername" . }}"
  registration-auth-password: "{{ include "dbaas.registrationPassword" . }}"
{{- end }}