{{- if eq (include "dbaas.enabled" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
    name: {{ template "dbaas-adapter.name" . }}
    component: dbaas-opensearch-adapter
  name: {{ template "dbaas-adapter.name" . }}-configs
data:
  {
    "osClusterVersion": "{{ .Values.dbaasAdapter.opensearchClusterVersion }}",
    "ncClusterVersion": "{{ .Values.dbaasAdapter.netcrackerOpensearchClusterVersion }}",
    "nodes": "{{ include "opensearch.nodes.count" . }}",
    "drMode": "{{ include "opensearch.enableDisasterRecovery" . }}",
    "installationMode": "{{ if eq (include "joint-mode" .) "true" }}joint{{ else }}separate{{ end }}"
  }
{{- end }}