{{- $secretName := include "dbaas-adapter.tlsSecretName" . }}
{{- $install := and (eq (include "dbaas-adapter.tlsEnabled" .) "true") (eq (include "dbaas.enabled" .) "true") ( or .Values.global.tls.generateCerts.enabled (eq (include "dbaas-adapter.certificatesSpecified" .) "true")) }}
{{- if and $install (ne (include "certProvider" .) "cert-manager") (not (lookup "v1" "Secret" .Release.Namespace $secretName)) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data: 
{{- if not .Values.global.tls.generateCerts.enabled }}
  {{- if .Values.dbaasAdapter.tls.certificates.crt }}
  tls.crt: {{ .Values.dbaasAdapter.tls.certificates.crt | quote }}
  {{- end }}
  {{- if .Values.dbaasAdapter.tls.certificates.key }}
  tls.key: {{ .Values.dbaasAdapter.tls.certificates.key | quote }}
  {{- end }}
  {{- if .Values.dbaasAdapter.tls.certificates.ca }}
  ca.crt: {{ .Values.dbaasAdapter.tls.certificates.ca | quote }}
  {{- end }}
{{- else }}
{{ include "dbaas-adapter.generateCerts" . | nindent 2 }}
{{- end }}
{{- end }}