apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "opensearch.fullname" . }}-service-operator
spec:
  replicas: {{ default 1 .Values.operator.replicas }}
  selector:
    matchLabels:
      name: {{ template "opensearch.fullname" . }}-service-operator
      component: opensearch-service-operator
  template:
    metadata:
      labels:
{{- with .Values.global.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{- with .Values.operator.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
        name: {{ template "opensearch.fullname" . }}-service-operator
        component: opensearch-service-operator
    spec:
      serviceAccountName: {{ template "opensearch.fullname" . }}-service-operator
      containers:
        - name: {{ template "opensearch.fullname" . }}-service-operator
          image: {{ template "operator.image" . }}
          ports:
            - containerPort: 8069
              protocol: TCP
              name: rep-health
          {{- if and .Values.opensearch.ssl.rest.enabled .Values.opensearch.ssl.rest.existingCertSecret }}
          volumeMounts:
            - mountPath: /certs/crt.pem
              name: certs
              subPath: {{ .Values.opensearch.ssl.rest.existingCertSecretCertSubPath }}
          {{- end }}
          command:
            - /manager
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPENSEARCH_HOST
            - name: OPENSEARCH_NAME
              value: {{ template "opensearch.fullname" . }}
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ template "opensearch.fullname" . }}-secret
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "opensearch.fullname" . }}-secret
          resources:
            limits:
              cpu: {{ default "100m" .Values.operator.resources.limits.cpu  }}
              memory: {{ default "128Mi" .Values.operator.resources.limits.memory }}
            requests:
              cpu: {{ default "25m" .Values.operator.resources.requests.cpu }}
              memory: {{ default "128Mi" .Values.operator.resources.requests.memory }}
        {{- if (eq (include "opensearch.enableDisasterRecovery" .) "true") }}
        - name: {{ template "opensearch.fullname" . }}-disaster-recovery
          image: {{ template "disasterRecovery.image" . }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8068
              protocol: TCP
              name: dr
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RESOURCE_FOR_DR
              value: "netcracker.com v1 opensearchservices {{ template "opensearch.fullname" . }}"
            - name: USE_DEFAULT_PATHS
              value: "true"
            - name: HEALTH_MAIN_SERVICES_ACTIVE
              value: "{{ trim (include "opensearch.statefulsetNames" .) }}"
            - name: HEALTH_MAIN_SERVICES_STANDBY
              value: "{{ trim (include "opensearch.statefulsetNames" .) }}"
            - name: HEALTH_MAIN_SERVICES_DISABLED
              value: "{{ trim (include "opensearch.statefulsetNames" .) }}"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ADDITIONAL_HEALTH_ENDPOINT
              value: http://$(POD_IP):8069/healthz
            {{- if .Values.global.disasterRecovery.httpAuth.enabled}}
            - name: SITE_MANAGER_NAMESPACE
              value: {{ .Values.global.disasterRecovery.httpAuth.smNamespace | quote }}
            - name: SITE_MANAGER_SERVICE_ACCOUNT_NAME
              value: {{ .Values.global.disasterRecovery.httpAuth.smServiceAccountName | quote }}
            {{- end }}
          resources:
            limits:
              cpu: {{ default "32m" .Values.global.disasterRecovery.resources.limits.cpu  }}
              memory: {{ default "32Mi" .Values.global.disasterRecovery.resources.limits.memory }}
            requests:
              cpu: {{ default "10m" .Values.global.disasterRecovery.resources.requests.cpu }}
              memory: {{ default "10Mi" .Values.global.disasterRecovery.resources.requests.memory }}
        {{- end }}
      {{- if and .Values.opensearch.ssl.rest.enabled .Values.opensearch.ssl.rest.existingCertSecret }}
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.opensearch.ssl.rest.existingCertSecret }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
