apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "opensearch.fullname" . }}-service-operator
spec:
  replicas: {{ default 1 .Values.operator.replicas }}
  selector:
    matchLabels:
      name: {{ template "opensearch.fullname" . }}-service-operator
      component: opensearch-service-operator
  template:
    metadata:
      labels:
{{- with .Values.global.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{- with .Values.operator.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
        name: {{ template "opensearch.fullname" . }}-service-operator
        component: opensearch-service-operator
      annotations:
        pre.hook.backup.velero.io/command: '["/bin/sh", "-c", "curl -u ${OPENSEARCH_USERNAME}:${OPENSEARCH_PASSWORD} ${OPENSEARCH_PROTOCOL:-http}://${OPENSEARCH_NAME}.${WATCH_NAMESPACE}:${OPENSEARCH_INTERNAL_SERVICE_PORT}/_flush"]'
    spec:
      serviceAccountName: {{ template "opensearch.fullname" . }}-service-operator
      containers:
        - name: {{ template "opensearch.fullname" . }}-service-operator
          image: {{ template "operator.image" . }}
          ports:
            - containerPort: 8069
              protocol: TCP
              name: rep-health
          {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
          volumeMounts:
            - mountPath: /certs/crt.pem
              name: opensearch-certs
              subPath: {{ template "opensearch.rest-root-ca-path" . }}
          {{- end }}
          command:
            - /manager
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPENSEARCH_PROTOCOL
              {{ if or .Values.global.externalOpensearch.enabled (eq (include "opensearch.tlsEnabled" .) "true") }}
              value: "https"
              {{ else }}
              value: "http"
              {{ end }}
            - name: OPENSEARCH_NAME
              value: {{ template "opensearch.fullname" . }}
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ template "opensearch.fullname" . }}-secret
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "opensearch.fullname" . }}-secret
          resources:
            limits:
              cpu: {{ default "100m" .Values.operator.resources.limits.cpu  }}
              memory: {{ default "128Mi" .Values.operator.resources.limits.memory }}
            requests:
              cpu: {{ default "25m" .Values.operator.resources.requests.cpu }}
              memory: {{ default "128Mi" .Values.operator.resources.requests.memory }}
        {{- if (eq (include "opensearch.enableDisasterRecovery" .) "true") }}
        - name: {{ template "opensearch.fullname" . }}-disaster-recovery
          image: {{ template "disasterRecovery.image" . }}
          imagePullPolicy: Always
          {{- if eq (include "disasterRecovery.tlsEnabled" .) "true" }}
          volumeMounts:
            - name: drd-certs
              mountPath: /tls
          {{- end }}
          ports:
            - containerPort: 8068
              protocol: TCP
              name: dr
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if eq (include "disasterRecovery.tlsEnabled" .) "true" }}
            - name: TLS_ENABLED
              value: "true"
            - name: CERTS_PATH
              value: "/tls"
            - name: CIPHER_SUITES
              value: "{{ include "disasterRecovery.cipherSuites" . }}"
            {{- end }}
            - name: RESOURCE_FOR_DR
              value: "netcracker.com v1 opensearchservices {{ template "opensearch.fullname" . }}"
            - name: USE_DEFAULT_PATHS
              value: "true"
            - name: HEALTH_MAIN_SERVICES_ACTIVE
              value: "{{ trim (include "opensearch.statefulsetNames" .) }}"
            - name: HEALTH_MAIN_SERVICES_STANDBY
              value: "{{ trim (include "opensearch.statefulsetNames" .) }}"
            - name: HEALTH_MAIN_SERVICES_DISABLED
              value: "{{ trim (include "opensearch.statefulsetNames" .) }}"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ADDITIONAL_HEALTH_ENDPOINT
              value: http://$(POD_IP):8069/healthz
            {{- if .Values.global.disasterRecovery.httpAuth.enabled}}
            - name: SITE_MANAGER_NAMESPACE
              value: {{ .Values.global.disasterRecovery.httpAuth.smNamespace | quote }}
            - name: SITE_MANAGER_SERVICE_ACCOUNT_NAME
              value: {{ .Values.global.disasterRecovery.httpAuth.smServiceAccountName | quote }}
            {{- end }}
          resources:
            limits:
              cpu: {{ default "32m" .Values.global.disasterRecovery.resources.limits.cpu  }}
              memory: {{ default "32Mi" .Values.global.disasterRecovery.resources.limits.memory }}
            requests:
              cpu: {{ default "10m" .Values.global.disasterRecovery.resources.requests.cpu }}
              memory: {{ default "10Mi" .Values.global.disasterRecovery.resources.requests.memory }}
        {{- end }}
      {{- if or (eq (include "opensearch.tlsEnabled" .) "true") (eq (include "disasterRecovery.tlsEnabled" .) "true") }}
      volumes:
        {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
        - name: opensearch-certs
          secret:
            secretName: {{ template "opensearch.rest-cert-secret-name" . }}
        {{- end }}
        {{- if eq (include "disasterRecovery.tlsEnabled" .) "true" }}
        - name: drd-certs
          secret:
            secretName: {{ template "disasterRecovery.certSecretName" . }}
        {{- end }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
