kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "opensearch.fullname" . }}-service-operator
subjects:
  - kind: ServiceAccount
    name: {{ template "opensearch.fullname" . }}-service-operator
roleRef:
  kind: Role
  name: {{ template "opensearch.fullname" . }}-service-operator
  apiGroup: rbac.authorization.k8s.io