dashboards:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: dashboards-opensearch-service-v2.ci-master.openshift.sdntest.netcracker.com
        paths:
          - path: /

opensearch:
  securityConfig:
    enabled: true
    path: "/usr/share/opensearch/config/opensearch-security"
    authc:
      basic:
        username: "netcrk"
        password: "crknet"
      oidc:
        openid_connect_url: "http://idp.framework-ci-services:8080/.well-known/openid-configuration"
  master:
    enabled: true
    replicas: 3
    persistence:
      enabled: true
      storageClass: "local-path"
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 250m
        memory: 2Gi
    javaOpts: "-Xms1024m -Xmx1024m"
  client:
    ingress:
      enabled: true
      path: /
      hosts:
        - opensearch-opensearch-service-v2.ci-master.openshift.sdntest.netcracker.com
  snapshots:
    enabled: true
    repositoryName: "snapshots"
    persistentVolume: "pv-opensearch-snapshots"
    persistentVolumeClaim: "pvc-opensearch-snapshots"
    size: 2Gi

monitoring:
  enabled: true
  includeIndices: true
  slowQueries:
    enabled: true
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200m

dbaasAdapter:
  enabled: true
  dbaasUsername: "dbaas-aggregator"
  dbaasPassword: "dbaas-aggregator"
  registrationAuthUsername: "cluster-dba"
  registrationAuthPassword: "Bnmq5567_PO"
  opensearchRepo: "snapshots"
  opensearchRepoRoot: "/usr/share/opensearch"
  apiVersion: v2
  resources:
    requests:
      memory: 32Mi
      cpu: 50m
    limits:
      memory: 32Mi
      cpu: 200m
  securityContext:
    runAsUser: 1000

curator:
  enabled: true
  snapshotRepositoryName: "snapshots"
  username: "admin"
  password: "admin"
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200m
  securityContext:
    runAsUser: 1000
    fsGroup: 1000