# permissions for end users to edit opensearchservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchservice-editor-role
rules:
- apiGroups:
  - qubership.org
  resources:
  - opensearchservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qubership.org
  resources:
  - opensearchservices/status
  verbs:
  - get
