
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - qubership.org
  resources:
  - opensearchservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qubership.org
  resources:
  - opensearchservices/finalizers
  verbs:
  - update
- apiGroups:
  - qubership.org
  resources:
  - opensearchservices/status
  verbs:
  - get
  - patch
  - update
