{
 "title": "OpenSearch Monitoring",
 "description": "InfluxDB dashboards for telegraf metrics",
 "tags": [
  "Prometheus",
  "OpenSearch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(opensearch_cluster_health_status_code, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(opensearch_cluster_health_status_code, namespace)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(opensearch_fs_total_available_in_bytes{namespace=\"$namespace\"}, node_name)"
    }
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,2m,5m,10m,30m,1h, 2h, 5h, 10h 1d"
   }
  ]
 },
 "panels": [
  { "title": "OpenSearch cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Status of OpenSearch cluster.\nIf the cluster status is `degraded`, at least one replica shard is unallocated or missing. The search\n   results will still be complete, but if more shards are missing, you may lose data.\n   \n   A `failed` cluster status indicates that:\n   \n    * At least one primary shard is missing.\n    * You are missing data.\n    * The searches will return partial results.\n    * You will be blocked from indexing into that shard.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(opensearch_cluster_health_status_code{namespace=\"$namespace\",cluster=\"$cluster\",status=\"\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opensearch_cluster_health",
     "query": "SELECT max(\"status_code\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes status",
   "type": "graph",
   "description": "Status of OpenSearch nodes",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "UP",
     "expr": "min(opensearch_cluster_health_number_of_nodes{namespace=\"$namespace\",cluster=\"$cluster\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Up",
     "query": "SELECT min(\"number_of_nodes\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DOWN",
     "expr": "scalar(opensearch_cluster_health_total_number_of_nodes{cluster=\"$cluster\",namespace=\"$namespace\"}) - min(opensearch_cluster_health_number_of_nodes{namespace=\"$namespace\",cluster=\"$cluster\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Down",
     "query": "SELECT last(\"total_number_of_nodes\") - min(\"number_of_nodes\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Maximum current CPU usage (in percent) among all OpenSearch servers.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$node_name\",container=\"opensearch\",cluster=\"$cluster\"}[5m])) / max(kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$namespace\",exported_pod=~\"$node_name\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Maximum current Memory usage (in percent) among all OpenSearch servers.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * max(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$node_name\",container=\"opensearch\",cluster=\"$cluster\"}) / max(container_spec_memory_limit_bytes{namespace=\"$namespace\", pod=~\"$node_name\", container=\"opensearch\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Status Transitions",
   "type": "natel-discrete-panel",
   "description": "Transitions of OpenSearch cluster status",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max(opensearch_cluster_health_status_code{namespace=\"$namespace\",cluster=\"$cluster\",status=\"\"})"
    }
   ]
  },
  {
   "title": "Pod Readiness Probe Transitions",
   "type": "natel-discrete-panel",
   "description": "Transitions of readiness probes for each OpenSearch pod.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "min(kube_pod_status_ready{exported_namespace=\"$namespace\", exported_pod=~\"$node_name\", condition=\"true\", cluster=\"$cluster\"}) by (exported_pod)",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "OpenSearch shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active primary shards",
     "type": "stat",
     "description": "The number of active primary shards in OpenSearch cluster",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_cluster_health_active_primary_shards{cluster=\"$cluster\",namespace=\"$namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_cluster_health",
       "query": "SELECT last(\"active_primary_shards\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Active shards",
     "type": "stat",
     "description": "The number of active primary and replica shards in OpenSearch cluster",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_cluster_health_active_shards{cluster=\"$cluster\",namespace=\"$namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_cluster_health",
       "query": "SELECT last(\"active_shards\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Initializing shards",
     "type": "stat",
     "description": "The number of shards that are in the `initializing` state. When you first create an index, or when a node is rebooted, its shards are briefly in the `initializing` state before transitioning to `started` or `unassigned` as the master node attempts to assign shards to nodes in the cluster. If you see the shards remain in the `initializing` state for too long, it could be a warning sign that your cluster is unstable.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_cluster_health_initializing_shards{cluster=\"$cluster\",namespace=\"$namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_cluster_health",
       "query": "SELECT last(\"initializing_shards\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Relocating shards",
     "type": "stat",
     "description": "The number of shards that are relocating now and have the `relocating` state.",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_cluster_health_relocating_shards{cluster=\"$cluster\",namespace=\"$namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_cluster_health",
       "query": "SELECT last(\"relocating_shards\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Unassigned shards",
     "type": "stat",
     "description": "The number of shards that are not assigned to any node and have the `unassigned` state. If you see the shards remain in the `unassigned` state for too long, it could be a warning sign that your cluster is unstable.",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(opensearch_cluster_health_unassigned_shards{cluster=\"$cluster\",namespace=\"$namespace\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_cluster_health",
       "query": "SELECT max(\"unassigned_shards\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "OpenSearch tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Tasks",
     "type": "stat",
     "description": "The number of tasks in 'pending' status in OpenSearch cluster",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Time of Most Waiting Task",
     "type": "graph",
     "description": "The maximum time in milliseconds that task is waiting in queue",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(opensearch_cluster_health_task_max_waiting_in_queue_millis{cluster=\"$cluster\",namespace=\"$namespace\"})",
       "legendFormat": "time of max waiting task"
      }
     ]
    }
   ]
  },
  {
   "title": "Network metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open transport connections",
     "type": "graph",
     "description": "The number of open transport connections for each OpenSearch node. May be not applicable for managed external OpenSearch.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name",
       "expr": "max(opensearch_transport_server_open{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}",
       "measurement": "opensearch_transport",
       "query": "SELECT max(\"server_open\") FROM \"opensearch_transport\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Open http connections",
     "type": "graph",
     "description": "The number of open HTTP connections for each OpenSearch node. If the total number of open HTTP connections is constantly increasing, it may indicate that your HTTP clients are not properly establishing persistent connections. Reestablishing connections adds extra milliseconds or even seconds to your request response time.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name.$col",
       "expr": "max(opensearch_http_current_open{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}",
       "measurement": "opensearch_http",
       "query": "SELECT max(\"current_open\") as \"open\" FROM \"opensearch_http\" WHERE (node_name =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Transport size",
     "type": "graph",
     "description": "The rate of change between subsequent size values of received (rx) and transmitted (tx) packages for each OpenSearch node. May be not applicable for managed external OpenSearch.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "_comment": "In the query 'count(rx_size_in_bytes) / count(rx_size_in_bytes)' part is added to have 'null' results, because by default 'non_negative_derivative' function returns nothing if interval does not contain values.",
       "alias": "$tag_node_name: rx",
       "expr": "sum(irate(opensearch_transport_rx_size_in_bytes{namespace=\"$namespace\",node_name=~\"^$node_name*\",cluster=\"$cluster\"}[$__interval])) by (node_name, node_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}[{{node_host}}:rx]",
       "measurement": "opensearch_transport",
       "query": "SELECT non_negative_derivative(mean(\"rx_size_in_bytes\"), 1s) * count(\"rx_size_in_bytes\") / count(\"rx_size_in_bytes\") FROM \"opensearch_transport\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "_comment": "In the query 'count(tx_size_in_bytes) / count(tx_size_in_bytes)' part is added to have 'null' results, because by default 'non_negative_derivative' function returns nothing if interval does not contain values.",
       "alias": "$tag_node_name: tx",
       "expr": "sum(irate(opensearch_transport_tx_size_in_bytes{namespace=\"$namespace\",node_name=~\"^$node_name*\",cluster=\"$cluster\"}[$__interval])) by (node_name, node_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}[{{node_host}}:tx]",
       "measurement": "opensearch_transport",
       "query": "SELECT non_negative_derivative(mean(\"tx_size_in_bytes\"), 1s) * count(\"tx_size_in_bytes\") / count(\"tx_size_in_bytes\") FROM \"opensearch_transport\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/) AND \"cluster\"=\"$cluster\" AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM heap and GC metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM heap usage",
     "type": "graph",
     "description": "The usage of JVM heap memory by each OpenSearch node",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name: $col",
       "expr": "sum(opensearch_jvm_mem_heap_used_in_bytes{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used:{{node_name}}",
       "measurement": "opensearch_jvm",
       "query": "SELECT mean(\"mem_heap_used_in_bytes\") AS \"used\", mean(\"mem_heap_max_in_bytes\") AS \"total\" FROM \"opensearch_jvm\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(opensearch_jvm_mem_heap_max_in_bytes{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "total:{{node_name}}"
      }
     ]
    },
    {
     "title": "JVM heap usage percent",
     "type": "graph",
     "description": "OpenSearch is set up to initiate garbage collections whenever JVM heap usage hits 75 percent. As shown above, it may be useful to monitor which nodes exhibit high heap usage, and set up an alert to find out if any node is consistently using over 85 percent of heap memory; this indicates that the rate of garbage collection isn’t keeping up with the rate of garbage creation. To address this problem, you can either increase your heap size (as long as it remains below the recommended guidelines stated above), or scale out the cluster by adding more nodes.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name",
       "expr": "sum(opensearch_jvm_mem_heap_used_percent{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}",
       "measurement": "opensearch_jvm",
       "query": "SELECT mean(\"mem_heap_used_percent\") FROM \"opensearch_jvm\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "JVM non heap usage",
     "type": "graph",
     "description": "The usage of memory outside the JVM heap by each OpenSearch node",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name: $col",
       "expr": "sum(opensearch_jvm_mem_non_heap_used_in_bytes{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}",
       "measurement": "opensearch_jvm",
       "query": "SELECT mean(\"mem_non_heap_used_in_bytes\") AS \"used\" FROM \"opensearch_jvm\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "description": "Time spent on major GCs that collect old generation objects and on minor GCs that collects young generation objects in JVM (time rate per sampling interval).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name: $col",
       "expr": "sum(irate(opensearch_jvm_gc_collectors_old_collection_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[$__interval])) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "old:{{node_name}}",
       "measurement": "opensearch_jvm",
       "query": "SELECT non_negative_difference(max(\"gc_collectors_old_collection_time_in_millis\")) * mean(\"gc_collectors_old_collection_time_in_millis\") / mean(\"gc_collectors_old_collection_time_in_millis\") AS \"old\", non_negative_difference(max(\"gc_collectors_young_collection_time_in_millis\")) * mean(\"gc_collectors_young_collection_time_in_millis\") / mean(\"gc_collectors_young_collection_time_in_millis\") AS \"young\" FROM \"opensearch_jvm\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(irate(opensearch_jvm_gc_collectors_young_collection_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[$__interval])) by (node_name)",
       "legendFormat": "young:{{node_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "OS memory usage",
     "type": "graph",
     "description": "The usage of memory by each OpenSearch node and its limit. These metric is useful to avoid reaching the memory limit on nodes.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_pod_name used",
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",pod=~\"$node_name\",container!=\"\",cluster=\"$cluster\"}) by (pod)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pod}}:allocated",
       "measurement": "memory/usage",
       "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE (\"pod_name\" =~ /^$node_name$*/ AND \"type\" = 'pod' AND \"namespace_name\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_pod_name total",
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\",exported_pod=~\"$node_name\",cluster=\"$cluster\"}) by (exported_pod)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{exported_pod}}:limit",
       "measurement": "memory/limit",
       "query": "SELECT mean(\"value\") FROM \"memory/limit\" WHERE (\"pod_name\" =~ /^$node_name$*/ AND \"type\" = 'pod' AND \"namespace_name\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$node_name\",container!=\"\",cluster=\"$cluster\"}) by (pod)",
       "legendFormat": "{{pod}}:usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage in percent",
     "type": "graph",
     "description": "The usage of disk space in percent for an OpenSearch node",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name [$tag_node_host] used",
       "expr": "100 * (((sum(opensearch_fs_total_total_in_bytes{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)) - (sum(opensearch_fs_total_free_in_bytes{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name))) / sum(opensearch_fs_total_total_in_bytes{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)) ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}",
       "measurement": "opensearch_fs",
       "query": "SELECT 100 * (mean(\"total_total_in_bytes\") - mean(\"total_free_in_bytes\")) / mean(\"total_total_in_bytes\") FROM \"opensearch_fs\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\" ,\"node_host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "graph",
     "description": "The usage of disk space allocated to each OpenSearch node and its limit",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name [$tag_node_host] total",
       "expr": "sum(opensearch_fs_total_total_in_bytes{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "total: {{node_name}}",
       "measurement": "opensearch_fs",
       "query": "SELECT mean(\"total_total_in_bytes\") FROM \"opensearch_fs\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\", \"node_host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_node_name [$tag_node_host] used",
       "expr": "sum(opensearch_fs_total_total_in_bytes{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name) - sum(opensearch_fs_total_available_in_bytes{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used: {{node_name}}",
       "measurement": "opensearch_fs",
       "query": "SELECT mean(\"total_total_in_bytes\") - mean( \"total_available_in_bytes\") FROM \"opensearch_fs\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY  time($__interval), \"node_name\", \"node_host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O operations",
     "type": "graph",
     "description": "The rate of change between subsequent values of input/output operations per second for each OpenSearch node",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "_comment": "In the query 'count(io_stats_total_read_operations) / count(io_stats_total_read_operations)' part is added to have 'null' results, because by default 'non_negative_derivative' function returns nothing if interval does not contain values.",
       "alias": "$tag_node_name [$tag_node_host] $col",
       "expr": "sum(irate(opensearch_fs_io_stats_total_write_operations{namespace=\"$namespace\",node_name=~\"^$node_name*\",cluster=\"$cluster\"}[$__interval])) by (node_name, node_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}[{{node_host}}]:write",
       "measurement": "opensearch_fs",
       "query": "SELECT non_negative_derivative(mean(\"io_stats_total_read_operations\"), 1s) * count(\"io_stats_total_read_operations\") / count(\"io_stats_total_read_operations\") AS \"read\", non_negative_derivative(mean(\"io_stats_total_write_operations\"), 1s) AS \"write\" FROM \"opensearch_fs\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\", \"node_host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(irate(opensearch_fs_io_stats_total_read_operations{namespace=\"$namespace\",node_name=~\"^$node_name*\",cluster=\"$cluster\"}[$__interval])) by (node_name, node_host)",
       "legendFormat": "{{node_name}}[{{node_host}}]:read"
      }
     ]
    },
    {
     "title": "Disk I/O usage",
     "type": "graph",
     "description": "The rate of change between subsequent values of disk usage for each OpenSearch node",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "_comment": "In the query 'count(io_stats_total_read_kilobytes) / count(io_stats_total_read_kilobytes)' part is added to have 'null' results, because by default 'non_negative_derivative' function returns nothing if interval does not contain values.",
       "alias": "$tag_node_name [$tag_node_host] $col",
       "expr": "sum(irate(opensearch_fs_io_stats_total_read_kilobytes{namespace=\"$namespace\",node_name=~\"^$node_name*\",cluster=\"$cluster\"}[$__interval])) by (node_name, node_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}[{{node_host}}:read]",
       "query": "SELECT non_negative_derivative(mean(\"io_stats_total_read_kilobytes\"), 1s) * count(\"io_stats_total_read_kilobytes\") / count(\"io_stats_total_read_kilobytes\") AS \"read\", non_negative_derivative(mean(\"io_stats_total_write_kilobytes\"), 1s) AS \"write\" FROM \"opensearch_fs\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\", \"node_host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(irate(opensearch_fs_io_stats_total_write_kilobytes{namespace=\"$namespace\",node_name=~\"^$node_name*\",cluster=\"$cluster\"}[$__interval])) by (node_name, node_host)",
       "legendFormat": "{{node_name}}[{{node_host}}:write]"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "description": "The amount of open file descriptors for each OpenSearch node",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(opensearch_process_open_file_descriptors{namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load average (5 min)",
     "type": "graph",
     "description": "Five-minute load average on the system",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name [$tag_node_host]",
       "expr": "sum(opensearch_os_cpu_load_average_5m{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name, node_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}} [{{node_host}}]",
       "measurement": "opensearch_os",
       "query": "SELECT mean(\"cpu_load_average_5m\") FROM \"opensearch_os\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\", \"node_host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU load in percent",
     "type": "graph",
     "description": "The usage of CPU in percent for each OpenSearch node",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name [$tag_node_host]",
       "expr": "sum(opensearch_process_cpu_percent{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name, node_host)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}[{{node_host}}]",
       "measurement": "opensearch_process",
       "query": "SELECT mean(\"cpu_percent\") FROM \"opensearch_process\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\", \"node_host\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU load by pod",
     "type": "graph",
     "description": "The usage of CPU by each OpenSearch node and its limit",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Millicores" }
     ],
     "targets": [
      {
       "alias": "$tag_pod_name",
       "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$node_name\",container!=\"\",cluster=\"$cluster\"}[5m])) by (pod)) * 1000",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Usage: {{pod}}",
       "measurement": "cpu/usage_rate",
       "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE (\"pod_name\" =~ /^$node_name$*/ AND \"type\" = 'pod' AND \"namespace_name\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_pod_name total",
       "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$namespace\",exported_pod=~\"$node_name\",cluster=\"$cluster\"}) by (exported_pod)) * 1000",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Limit: {{exported_pod}}",
       "measurement": "cpu/limit",
       "query": "SELECT mean(\"value\") FROM \"cpu/limit\" WHERE (\"pod_name\" =~ /^$node_name$*/ AND \"type\" = 'pod' AND \"namespace_name\" =~ /^$namespace$/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Indices statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indices total operations",
     "type": "graph",
     "description": "The number of operations performed by indices at the moment grouped by operation type and OpenSearch node",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name: $col",
       "expr": "sum(opensearch_indices_flush_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:flush",
       "measurement": "opensearch_indices",
       "query": "SELECT  mean(flush_total) as \"flush\", mean(get_exists_total) as \"get-exists\", mean(get_missing_total) as \"get-missing\", mean(get_total) as \"get\", mean(indexing_delete_total) as \"indexing-delete\", mean(indexing_index_total) as \"indexing-index\", mean(indexing_noop_update_total) as \"indexing-noop-update\", mean(merges_total) as \"merges\", mean(percolate_total) as \"percolate\", mean(refresh_total) as \"refresh\", mean(search_fetch_total) as \"search-fetch\", mean(search_query_total) as \"search-query\", mean(search_scroll_total) as \"search-scroll\", mean(suggest_total) as \"suggest\", mean(warmer_total) as \"warmer\" FROM \"opensearch_indices\" WHERE (node_name =~ /$node_name/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY time($__interval), * fill(null)"
      },
      {
       "expr": "sum(opensearch_indices_get_exists_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:get-exists"
      },
      {
       "expr": "sum(opensearch_indices_get_missing_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:get-missing"
      },
      {
       "expr": "sum(opensearch_indices_get_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}: get"
      },
      {
       "expr": "sum(opensearch_indices_indexing_delete_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-delete"
      },
      {
       "expr": "sum(opensearch_indices_indexing_index_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-index"
      },
      {
       "expr": "sum(opensearch_indices_indexing_noop_update_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-noop-update"
      },
      {
       "expr": "sum(opensearch_indices_merges_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:merges"
      },
      {
       "expr": "sum(opensearch_indices_percolate_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:percolate"
      },
      {
       "expr": "sum(opensearch_indices_refresh_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:refresh"
      },
      {
       "expr": "sum(opensearch_indices_search_fetch_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:search-fetch"
      },
      {
       "expr": "sum(opensearch_indices_search_query_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:search-query"
      },
      {
       "expr": "sum(opensearch_indices_search_scroll_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:search-scroll"
      },
      {
       "expr": "sum(opensearch_indices_suggest_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:suggest"
      },
      {
       "expr": "sum(opensearch_indices_warmer_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:warmer"
      }
     ]
    },
    {
     "title": "Indices operations rate",
     "type": "graph",
     "description": "The operations number performed by indices per second grouped by operation type and OpenSearch node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(opensearch_indices_flush_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:flush"
      },
      {
       "expr": "sum(rate(opensearch_indices_get_exists_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:get-exists"
      },
      {
       "expr": "sum(rate(opensearch_indices_get_missing_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:get-missing"
      },
      {
       "expr": "sum(rate(opensearch_indices_get_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:get"
      },
      {
       "expr": "sum(rate(opensearch_indices_indexing_delete_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-delete"
      },
      {
       "expr": "sum(rate(opensearch_indices_indexing_index_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-index"
      },
      {
       "expr": "sum(rate(opensearch_indices_indexing_noop_update_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-noop-update"
      },
      {
       "expr": "sum(rate(opensearch_indices_merges_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:merges"
      },
      {
       "expr": "sum(rate(opensearch_indices_percolate_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:percolate"
      },
      {
       "expr": "sum(rate(opensearch_indices_refresh_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:refresh"
      },
      {
       "expr": "sum(rate(opensearch_indices_search_fetch_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:search-fetch"
      },
      {
       "expr": "sum(rate(opensearch_indices_search_query_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:search-query"
      },
      {
       "expr": "sum(rate(opensearch_indices_search_scroll_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:search-scroll"
      },
      {
       "expr": "sum(rate(opensearch_indices_suggest_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:suggest"
      },
      {
       "expr": "sum(rate(opensearch_indices_warmer_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:warmer"
      }
     ]
    },
    {
     "title": "Indices time operations",
     "type": "graph",
     "description": "The average time to complete an operation in indices grouped by operation type and OpenSearch node",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name: $col",
       "expr": "sum(opensearch_indices_merges_total_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}:merges-total",
       "measurement": "opensearch_transport_rx_count",
       "query": "SELECT mean(merges_total_time_in_millis) AS \"merges-total\", mean(flush_total_time_in_millis) AS \"flush-total\", mean(get_exists_time_in_millis) AS \"get-exists\", mean(get_missing_time_in_millis) AS \"get-missing\", mean(get_time_in_millis) AS \"get\", mean(indexing_delete_time_in_millis) AS \"indexing-delete\", mean(indexing_index_time_in_millis) AS \"indexing-index\", mean(indexing_throttle_time_in_millis) AS \"indexing-throttle\", mean(merges_total_stopped_time_in_millis) AS \"merges-total-stopped\", mean(merges_total_throttled_time_in_millis) AS \"merges-total-throttled\", mean(merges_total_time_in_millis) AS \"merges-total\", mean(percolate_time_in_millis) AS \"percolate\", mean(recovery_throttle_time_in_millis) AS \"recovery-throttle\", mean(refresh_total_time_in_millis) AS \"refresh-total\", mean(search_fetch_time_in_millis) AS \"search-fetch\", mean(search_query_time_in_millis) AS \"search-query\", mean(search_scroll_time_in_millis) AS \"search-scroll\", mean(store_throttle_time_in_millis) AS \"store-throttle\", mean(suggest_time_in_millis) AS \"suggest\", mean(warmer_total_time_in_millis) AS \"warmer-total\" FROM \"opensearch_indices\" WHERE (node_name =~ /$node_name/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY time($__interval), * fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(opensearch_indices_flush_total_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:flush-total"
      },
      {
       "expr": "sum(opensearch_indices_get_exists_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:get-exists"
      },
      {
       "expr": "sum(opensearch_indices_get_missing_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:get-missing"
      },
      {
       "expr": "sum(opensearch_indices_get_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:get"
      },
      {
       "expr": "sum(opensearch_indices_indexing_delete_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-delete"
      },
      {
       "expr": "sum(opensearch_indices_indexing_index_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-index"
      },
      {
       "expr": "sum(opensearch_indices_indexing_throttle_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-throttle"
      },
      {
       "expr": "sum(opensearch_indices_merges_total_stopped_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:merges-total-stopped"
      },
      {
       "expr": "sum(opensearch_indices_merges_total_throttled_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:merges-total-throttled"
      },
      {
       "expr": "sum(opensearch_indices_percolate_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:percolate"
      },
      {
       "expr": "sum(opensearch_indices_recovery_throttle_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:recovery-throttle"
      },
      {
       "expr": "sum(opensearch_indices_refresh_total_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:refresh-total"
      },
      {
       "expr": "sum(opensearch_indices_search_fetch_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:search-fetch"
      },
      {
       "expr": "sum(opensearch_indices_search_query_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:search-query"
      },
      {
       "expr": "sum(opensearch_indices_search_scroll_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:search-scroll"
      },
      {
       "expr": "sum(opensearch_indices_store_throttle_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:store-throttle"
      },
      {
       "expr": "sum(opensearch_indices_suggest_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:suggest"
      },
      {
       "expr": "sum(opensearch_indices_warmer_total_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:warmer-total"
      }
     ]
    },
    {
     "title": "Indices time operations rate",
     "type": "graph",
     "description": "The average time to complete an operation in indices per second grouped by operation type and OpenSearch node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ms/sec" }
     ],
     "targets": [
      {
       "expr": "sum(rate(opensearch_indices_merges_total_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:merges-total"
      },
      {
       "expr": "sum(rate(opensearch_indices_flush_total_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:flush-total"
      },
      {
       "expr": "sum(rate(opensearch_indices_get_exists_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:get-exists"
      },
      {
       "expr": "sum(rate(opensearch_indices_get_missing_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:get-missing"
      },
      {
       "expr": "sum(rate(opensearch_indices_get_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:get"
      },
      {
       "expr": "sum(rate(opensearch_indices_indexing_delete_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-delete"
      },
      {
       "expr": "sum(rate(opensearch_indices_indexing_index_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-index"
      },
      {
       "expr": "sum(rate(opensearch_indices_indexing_throttle_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:indexing-throttle"
      },
      {
       "expr": "sum(rate(opensearch_indices_merges_total_stopped_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:merges-total-stopped"
      },
      {
       "expr": "sum(rate(opensearch_indices_merges_total_throttled_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:merges-total-throttled"
      },
      {
       "expr": "sum(rate(opensearch_indices_percolate_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:percolate"
      },
      {
       "expr": "sum(rate(opensearch_indices_recovery_throttle_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:recovery-throttle"
      },
      {
       "expr": "sum(rate(opensearch_indices_refresh_total_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:refresh-total"
      },
      {
       "expr": "sum(rate(opensearch_indices_search_fetch_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:search-fetch"
      },
      {
       "expr": "sum(rate(opensearch_indices_search_query_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:search-query"
      },
      {
       "expr": "sum(rate(opensearch_indices_search_scroll_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:search-scroll"
      },
      {
       "expr": "sum(rate(opensearch_indices_store_throttle_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:store-throttle"
      },
      {
       "expr": "sum(rate(opensearch_indices_suggest_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:suggest"
      },
      {
       "expr": "sum(rate(opensearch_indices_warmer_total_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{node_name}}:warmer-total"
      }
     ]
    },
    {
     "title": "Indices current operations",
     "type": "graph",
     "description": "The number of operations performed by indices in the moment grouped by operation type and OpenSearch node",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name: $col",
       "expr": "sum(opensearch_indices_get_current{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}:get",
       "measurement": "opensearch_indices",
       "query": "SELECT mean(\"get_current\") AS \"get\", mean(\"indexing_index_current\") AS \"index\", mean(\"search_fetch_current\") AS \"search fetch\", mean(\"search_query_current\") AS \"search query\" FROM \"opensearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(opensearch_indices_indexing_index_current{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:index"
      },
      {
       "expr": "sum(opensearch_indices_search_fetch_current{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:search fetch"
      },
      {
       "expr": "sum(opensearch_indices_search_query_current{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:search query"
      }
     ]
    },
    {
     "title": "Indices data size",
     "type": "graph",
     "description": "The size of data stored in indices grouped by OpenSearch nodes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "indices size",
       "expr": "sum(opensearch_indices_store_size_in_bytes{node_name=~\"^$node_name$\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ node_name }}",
       "measurement": "opensearch_clusterstats_indices",
       "query": "SELECT mean(\"store_size_in_bytes\") FROM \"opensearch_clusterstats_indices\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"cluster_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Indices documents count",
     "type": "graph",
     "description": "The number of documents stored in indices grouped by OpenSearch nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "document count",
       "expr": "sum(opensearch_indices_docs_count{node_name=~\"^$node_name$\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ node_name }}",
       "measurement": "opensearch_clusterstats_indices",
       "query": "SELECT mean(\"docs_count\") FROM \"opensearch_clusterstats_indices\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"cluster_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Indices documents rate",
     "type": "graph",
     "description": "The number of documents added to indices per second grouped by OpenSearch nodes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(opensearch_indices_docs_count{node_name=~\"^$node_name$\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m])) by (node_name)",
       "legendFormat": "{{ node_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread pool queues and requests metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests latency",
     "type": "graph",
     "description": "If you notice the indexing latency increasing, you may be trying to index too many documents at one time (OpenSearch’s documentation recommends starting with a bulk indexing size of 5 to 15 megabytes and increasing slowly from there).\nIf you are planning to index a lot of documents and you don’t need the new information to be immediately available for search, you can optimize for indexing performance over search performance by decreasing refresh frequency until you are done indexing.\nFlush latency:  If you see this metric increasing steadily, it could indicate a problem with slow disks",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name: indexing",
       "expr": "sum(opensearch_indices_indexing_index_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name) / sum(opensearch_indices_indexing_index_total{node_name=~\"^$node_name*\",namespace=\"$namespace\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}:indexing",
       "measurement": "opensearch_indices",
       "query": "SELECT mean(\"indexing_index_time_in_millis\") / mean(\"indexing_index_total\") FROM \"opensearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY \"node_name\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_node_name: flush",
       "expr": "sum(opensearch_indices_flush_total_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name) / sum(opensearch_indices_flush_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}:flush",
       "measurement": "opensearch_indices",
       "query": "SELECT mean(\"flush_total_time_in_millis\") / mean(\"flush_total\") FROM \"opensearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY \"node_name\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_node_name: get exists",
       "expr": "sum(opensearch_indices_get_exists_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name) / sum(opensearch_indices_get_exists_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}:get exists",
       "query": "SELECT mean(\"get_exists_time_in_millis\") / mean(\"get_exists_total\") FROM \"opensearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY \"node_name\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_node_name: search query",
       "expr": "sum(opensearch_indices_search_query_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name) / sum(opensearch_indices_search_query_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}:search query",
       "query": "SELECT mean(\"search_query_time_in_millis\") / mean(\"search_query_total\") FROM \"opensearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY \"node_name\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_node_name: fetch query",
       "expr": "sum(opensearch_indices_search_fetch_time_in_millis{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name) / sum(opensearch_indices_search_fetch_total{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}: fetch query",
       "query": "SELECT mean(\"search_fetch_time_in_millis\") / mean(\"search_fetch_total\") FROM \"opensearch_indices\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY \"node_name\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Rejected requests",
     "type": "graph",
     "description": "The size of each thread pool’s queue represents how many requests are waiting to be served while the node is currently at capacity. The queue allows the node to track and eventually serve these requests instead of discarding them. Thread pool rejections arise once the thread pool’s maximum queue size (which varies based on the type of thread pool) is reached.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name: $col",
       "expr": "max(opensearch_thread_pool_write_rejected{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}:write",
       "measurement": "opensearch_thread_pool",
       "query": "SELECT max(\"bulk_rejected\") AS \"bulk\", max(\"get_rejected\") AS \"get\", max(\"index_rejected\") AS \"index\", max(\"search_rejected\") AS \"search\" FROM \"opensearch_thread_pool\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "max(opensearch_thread_pool_get_rejected{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:get"
      },
      {
       "expr": "max(opensearch_thread_pool_index_rejected{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:index"
      },
      {
       "expr": "max(opensearch_thread_pool_search_rejected{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:search"
      }
     ]
    },
    {
     "title": "Thread pool queues",
     "type": "graph",
     "description": "The size of each thread pool’s queue represents how many requests are waiting to be served while the node is currently at capacity.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_node_name: $col",
       "expr": "max(opensearch_thread_pool_write_queue{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{node_name}}:write",
       "measurement": "opensearch_thread_pool",
       "query": "SELECT max(\"bulk_queue\") AS \"bulk\", max(\"flush_queue\") AS \"flush\", max(\"get_queue\") AS \"get\", max(\"index_queue\") AS \"index\", max(\"refresh_queue\") AS \"refresh\", max(\"search_queue\") AS \"search\" FROM \"opensearch_thread_pool\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "max(opensearch_thread_pool_flush_queue{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:flush"
      },
      {
       "expr": "max(opensearch_thread_pool_get_queue{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:get"
      },
      {
       "expr": "max(opensearch_thread_pool_index_queue{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:index"
      },
      {
       "expr": "max(opensearch_thread_pool_refresh_queue{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:refresh"
      },
      {
       "expr": "max(opensearch_thread_pool_search_queue{node_name=~\"^$node_name*\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (node_name)",
       "legendFormat": "{{node_name}}:search"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup Daemon Status",
     "type": "stat",
     "description": "Shows the current activity status of the backup daemon. The activity status can be one of following:\n* Not Active - There is no running backup process.\n* In Progress/Started - The backup process is running.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_backups_metric_current_status{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_backups_metric",
       "query": "SELECT last(\"current_status\") FROM \"opensearch_backups_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Backup Status",
     "type": "stat",
     "description": "Shows the state of the last backup. The backup status can be one of following:\n \n* SUCCESS - There is at least one successful backup, and the latest backup is successful.\n* FAILED - There are no successful backups, or the last backup failed.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_backups_metric_last_backup_status{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_backups_metric",
       "query": "SELECT last(\"last_backup_status\") FROM \"opensearch_backups_metric\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Time of Last Backup",
     "type": "stat",
     "description": "Shows the period of time when the last backup process was ended.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_backups_metric_last_snapshot_time{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_backups_metric",
       "query": "SELECT last(\"last_snapshot_time\") FROM \"opensearch_backups_metric\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backup Daemon Status Transitions",
     "type": "natel-discrete-panel",
     "description": "Shows the current activity status of the backup daemon. The activity status can be one of following:\n* Not Active - There is no running backup process.\n* In Progress/Started - The backup process is running.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "opensearch_backups_metric_current_status{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "elasticsearch_backups_metric",
       "query": "SELECT last(\"current_status\") FROM \"elasticsearch_backups_metric\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Storage Type",
     "type": "stat",
     "description": "Shows the backup storage type.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_backups_metric_storage_type{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_backups_metric",
       "query": "SELECT last(\"storage_type\") FROM \"opensearch_backups_metric\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Successful Backup Versions Count",
     "type": "stat",
     "description": "Shows the amount of successful backups.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_backups_metric_count_of_successful_snapshots{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_backups_metric",
       "query": "SELECT last(\"count_of_successful_snapshots\") FROM \"opensearch_backups_metric\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Time of Last Successful Backup",
     "type": "stat",
     "description": "Shows the period of time when the last successful backup process was ended.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_backups_metric_last_snapshot_time{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_backups_metric",
       "query": "SELECT last(\"last_snapshot_time\") FROM \"opensearch_backups_metric\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backup Versions Count",
     "type": "stat",
     "description": "Shows the amount of available backups.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "opensearch_backups_metric_count_of_snapshots{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_backups_metric",
       "query": "SELECT last(\"count_of_snapshots\") FROM \"opensearch_backups_metric\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Storage Size/Free Space",
     "type": "graph",
     "description": "Shows the space occupied by backups and the remaining amount of space. \nNot all storage supports total size, so \"Total Volume Space\" metrics can be zeroed.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Space Used",
       "expr": "sum(opensearch_fs_total_total_in_bytes{namespace=\"$namespace\",cluster=\"$cluster\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "total",
       "measurement": "opensearch_fs",
       "query": "SELECT (mean(\"total_total_in_bytes\") - mean(\"total_free_in_bytes\")) FROM \"opensearch_fs\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Total Volume Space",
       "expr": "sum(opensearch_fs_total_total_in_bytes{namespace=\"$namespace\",cluster=\"$cluster\"}) - sum(opensearch_fs_total_free_in_bytes{namespace=\"$namespace\",cluster=\"$cluster\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "usage",
       "measurement": "opensearch_fs",
       "query": "SELECT mean(\"total_total_in_bytes\") FROM \"opensearch_fs\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backup Activity Status",
     "type": "graph",
     "description": "Shows the changes of activity status on the chart.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Time Spent on Each Backup",
       "expr": "sum(opensearch_backups_metric_last_backup_time_spent{namespace=\"$namespace\",cluster=\"$cluster\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_backups_metric",
       "query": "SELECT mean(\"last_backup_time_spent\") FROM \"opensearch_backups_metric\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Time Spent on Backup",
     "type": "graph",
     "description": "Shows time spent on last backup.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(opensearch_backups_metric_last_backup_time_spent{namespace=\"$namespace\",cluster=\"$cluster\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_backups_metric",
       "query": "SELECT mean(\"last_backup_time_spent\") FROM \"opensearch_backups_metric\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backup Last Version Size",
     "type": "graph",
     "description": "Shows the size of the last backup.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "opensearch_backups_metric_last_backup_size{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_backups_metric",
       "query": "SELECT last(\"last_backup_size\") FROM \"opensearch_backups_metric\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DBaaS Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "DBaaS Adapter Status",
     "type": "blackmirror1-singlestat-math-panel",
     "description": "The status of DBaaS Adapter.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "opensearch_dbaas_health_status{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_dbaas_health",
       "query": "SELECT last(\"status\") FROM \"opensearch_dbaas_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DBaaS OpenSearch Cluster Status",
     "type": "blackmirror1-singlestat-math-panel",
     "description": "The status of OpenSearch cluster from the DBaaS Adapter side",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "alias": "Status",
       "expr": "opensearch_dbaas_health_elastic_cluster_status{namespace=\"$namespace\",cluster=\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "opensearch_dbaas_health",
       "query": "SELECT last(\"elastic_cluster_status\")  / 5 FROM \"opensearch_dbaas_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DBaaS Adapter Status Transitions",
     "type": "natel-discrete-panel",
     "description": "Transitions of DBaaS Adapter statuses",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "opensearch_dbaas_health_status{namespace=\"$namespace\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "DBaaS OpenSearch Cluster Status Transitions",
     "type": "natel-discrete-panel",
     "description": "Transitions of DBaaS OpenSearch cluster status",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "opensearch_dbaas_health_elastic_cluster_status{namespace=\"$namespace\",cluster=\"$cluster\"}"
      }
     ]
    }
   ]
  }
 ]
}