{
 "title": "OpenSearch Replication",
 "description": "OpenSearch Replication",
 "tags": [
  "prometheus",
  "opensearch",
  "replication"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(opensearch_cluster_health_status_code, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(opensearch_cluster_health_status_code, namespace)"
    }
   },
   {
    "name": "index",
    "label": "Index",
    "query": {
     "query": "label_values(opensearch_replication_metric_index_status{namespace=\"$namespace\",index=~\"$indices_regex\",cluster=\"$cluster\"}, index)"
    }
   },
   { "name": "indices_regex", "label": "Indices Regex", "query": ".*" },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,2m,5m,10m,30m,1h, 2h, 5h, 10h 1d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "OpenSearch Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Replication status",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Status of OpenSearch cross-cluster replication.\n\nIf the cluster status is `Degraded`, at least one replicated indices is in `Failed` state. \n   \nA `Failed` replication status indicates that all indices are in `Failed` state.\n\nA `Not in progress` status means that replication from remote cluster disabled.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(opensearch_replication_metric_status{namespace=\"$namespace\",cluster=\"$cluster\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opensearch_cluster_health",
     "query": "SELECT max(\"status_code\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Syncing indices",
   "type": "stat",
   "description": "The number of indices that are in the `Syncing` state.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_replication_metric_syncing_indices{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opensearch_cluster_health",
     "query": "SELECT last(\"initializing_shards\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bootstrapping indices",
   "type": "stat",
   "description": "The number of indices that are in the `Bootstrapping` state.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_replication_metric_bootstrapping_indices{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opensearch_cluster_health",
     "query": "SELECT last(\"initializing_shards\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Paused indices",
   "type": "stat",
   "description": "The number of indices that are in the `Paused` state.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_replication_metric_paused_indices{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opensearch_cluster_health",
     "query": "SELECT last(\"initializing_shards\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed indices",
   "type": "stat",
   "description": "The number of indices that are in the `Failed` state.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_replication_metric_failed_indices{cluster=\"$cluster\",namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "opensearch_cluster_health",
     "query": "SELECT last(\"initializing_shards\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication status transitions",
   "type": "natel-discrete-panel",
   "description": "Transitions of OpenSearch replication status",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "max(opensearch_replication_metric_status{namespace=\"$namespace\",cluster=\"$cluster\",status=\"\"})"
    }
   ]
  },
  {
   "title": "Indices status",
   "type": "table",
   "description": "Status of OpenSearch replicated indices",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "UP",
     "expr": "opensearch_replication_metric_index_status{namespace=\"$namespace\",cluster=\"$cluster\", index=~\"$index\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "query": "SELECT min(\"number_of_nodes\") FROM \"opensearch_cluster_health\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices status transitions",
   "type": "natel-discrete-panel",
   "description": "Transitions of status for OpenSearch replicated indices",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "opensearch_replication_metric_index_status{namespace=\"$namespace\", index=~\"$index\", cluster=\"$cluster\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Syncing indices lag",
   "type": "graph",
   "description": "The replication lag between leader and follower sides. Evaluated as difference between `leader_checkpoint` and `follower_checkpoint`.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "expr": "max(opensearch_replication_metric_index_lag{index=~\"$index\",namespace=\"$namespace\",cluster=\"$cluster\"}) by (index)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{index}}",
     "measurement": "opensearch_transport",
     "query": "SELECT max(\"server_open\") FROM \"opensearch_transport\" WHERE (\"node_name\" =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Syncing indices rate",
   "type": "graph",
   "description": "Cross-cluster replication rate per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name.$col",
     "expr": "max(abs(rate(opensearch_replication_metric_index_rate{index=~\"$index\",namespace=\"$namespace\",cluster=\"$cluster\"}[5m]))) by (index)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{index}}",
     "measurement": "opensearch_http",
     "query": "SELECT max(\"current_open\") as \"open\" FROM \"opensearch_http\" WHERE (node_name =~ /^$node_name$/ AND \"namespace\" =~ /^$namespace$/ AND \"cluster\"=\"$cluster\") AND $timeFilter GROUP BY time($__interval), \"node_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}