{
 "title": "OpenSearch Indices",
 "description": "OpenSearch Indices",
 "tags": [
  "prometheus",
  "opensearch",
  "opensearch_name_and_namespace",
  "indices"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(opensearch_cluster_health_status_code, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(opensearch_cluster_health_status_code{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "index",
    "label": "Index",
    "query": "label_values(opensearch_indices_stats_primaries_docs_count{namespace=\"$namespace\",index_name=~\"$indices_regex\",cluster=\"$cluster\"}, index_name)"
   },
   { "name": "indices_regex", "label": "Indices Regex", "query": ".*" },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Indices Information",
   "type": "table",
   "description": "The number of documents and size in bytes for each index in descending order of size values",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(opensearch_indices_stats_primaries_docs_count{namespace=\"$namespace\",index_name=~\"$index\",cluster=\"$cluster\"}) by (index_name)"
    },
    {
     "expr": "sum(opensearch_indices_stats_primaries_store_size_in_bytes{namespace=\"$namespace\",index_name=~\"$index\",cluster=\"$cluster\"}) by (index_name)"
    }
   ]
  },
  {
   "title": "Indices by OpenSearch Version",
   "type": "table",
   "description": "Count of indices grouped by OpenSearch version. Indices created in OpenSearch 1.x should be migrated.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "opensearch_indices_version_created_count{namespace=\"$namespace\",cluster=\"$cluster\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Incoming Documents Rate per Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$index",
   "type": "timeseries",
   "description": "The number of documents added to index on primary shards per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "repeat": "index",
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(opensearch_indices_stats_primaries_docs_count{namespace=\"$namespace\",index_name=~\"$index\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "primary"
    }
   ]
  },
  {
   "title": "Store Size per Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$index",
   "type": "timeseries",
   "description": "The size in bytes occupied by index on primary shards and in total",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "repeat": "index",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_indices_stats_primaries_store_size_in_bytes{namespace=\"$namespace\",index_name=~\"$index\",cluster=\"$cluster\"}",
     "legendFormat": "primary"
    },
    {
     "expr": "opensearch_indices_stats_total_store_size_in_bytes{namespace=\"$namespace\",index_name=~\"$index\",cluster=\"$cluster\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Indexing Documents Rate per Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$index",
   "type": "timeseries",
   "description": "The number of indexing operations in index per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "repeat": "index",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(opensearch_indices_stats_primaries_indexing_index_total{namespace=\"$namespace\",index_name=~\"$index\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "primary"
    }
   ]
  },
  {
   "title": "Deleting Documents Rate per Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$index",
   "type": "timeseries",
   "description": "The number of deleted documents from index per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "repeat": "index",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(opensearch_indices_stats_primaries_docs_deleted{namespace=\"$namespace\",index_name=~\"$index\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "primary"
    }
   ]
  }
 ]
}