global:
  imagePullSecrets:
    - name: github-registry

dashboards:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: dashboards-opensearch-service.example.com
        paths:
          - path: /

opensearch:
  sysctl:
    enabled: true
  securityConfig:
    authc:
      basic:
        username: "netcrk"
        password: "crknet"

  master:
    enabled: true
    replicas: 3
    persistence:
      enabled: true
      storageClass: "default"
    resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 250m
        memory: 2Gi
    javaOpts: "-Xms1024m -Xmx1024m"
  client:
    ingress:
      enabled: true
      path: /
      hosts:
        - opensearch-opensearch-service.example.com
  snapshots:
    enabled: true
    storageClass: "default"
    size: 2Gi

monitoring:
  enabled: true

dbaasAdapter:
  enabled: false

curator:
  enabled: true
  username: "admin"
  password: "admin"
