version: '3'
services:
  operator-sdk:
    build:
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../:/opensearch-service-operator
      - ../docs:/docs
    working_dir: /opensearch-service-operator
