build:
  env:
    type: application-integration
    version: openshift-dd-2
  networkRules: integration
  integration:
    multi_image_descriptor: true
    dmp_descriptor:
      version: '1.12'

publication:
  application-manifest:
    am-mf: application.mf
    am-zip: application.zip

deployment:
  availability_check: true
  availability:
    resource: Job
    conditions: Successful
    interval: 30
    max_tries: 20
    delay: 30
  mode: reinstall
  values:
    dashboards:
      enabled: true

    opensearch:
      securityConfig:
        enabled: true
        path: "/usr/share/opensearch/plugins/opensearch-security/securityconfig"
        authc:
          basic:
            username: "netcrk"
            password: "crknet"
          oidc:
            openid_connect_url: "http://identity-management-security-services-ci.dr311dev.openshift.sdntest.netcracker.com/.well-known/openid-configuration"
      master:
        enabled: true
        replicas: 3
        persistence:
          enabled: true
          storageClass: "local-path"
        resources:
          limits:
            cpu: 500m
            memory: 1536Mi
          requests:
            cpu: 50m
            memory: 1536Mi
      client:
        ingress:
          enabled: true
          path: /
          hosts:
            - opensearch-opensearch-service.ci-master.openshift.sdntest.netcracker.com
      snapshots:
        enabled: true
        repositoryName: "snapshots"
        persistentVolume: "pv-opensearch-snapshots"
        persistentVolumeClaim: "pvc-opensearch-snapshots"
        size: 2Gi

    monitoring:
      enabled: true
      resources:
        requests:
          memory: 256Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 200m

    dbaasAdapter:
      enabled: true
      dbaasUsername: "dbaas-aggregator"
      dbaasPassword: "dbaas-aggregator"
      registrationAuthUsername: "cluster-dba"
      registrationAuthPassword: "Bnmq5567_PO"
      opensearchRepo: "snapshots"
      opensearchRepoRoot: "/usr/share/opensearch"
      resources:
        requests:
          memory: 32Mi
          cpu: 50m
        limits:
          memory: 32Mi
          cpu: 200m
      securityContext:
        runAsUser: 1000

    curator:
      enabled: true
      snapshotRepositoryName: "snapshots"
      username: "admin"
      password: "admin"
      resources:
        requests:
          memory: 256Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 200m
      securityContext:
        runAsUser: 1000
        fsGroup: 1000

cloud:
  type: helm
  url: https://ci-master.openshift.sdntest.netcracker.com:6443
  project: opensearch-service

integration:
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/opensearch-service
    location: v.0.0.2
    docker-image-id: timestamp
    deploy-param: opensearchOperator
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.Streaming/disaster-recovery-daemon
    location: 0.0.2
    docker-image-id: timestamp
    deploy-param: disasterRecoveryImage
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/opensearch-service
    location: v.0.0.2
    prefix: integration-tests
    docker-image-id: timestamp
    deploy-param: opensearchIntegrationTests
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/docker-opensearch
    location: 0.0.1
    docker-image-id: timestamp
    deploy-param: dockerOpensearch
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/elasticsearch-telegraf
    location: v.6.8.23-1.6
    docker-image-id: timestamp
    deploy-param: opensearchMonitoring
  # - type: find-latest-deployment-descriptor
  #   repo: PROD.Platform.ElasticStack/dbaas_elasticsearch
  #   location: master
  #   docker-image-id: timestamp
  #   deploy-param: opensearchDbaasAdapter
  - type: image
    docker-image: artifactorycn.netcracker.com:17014/product/prod.platform.elasticstack_dbaas_elasticsearch:1.0.20_20220311-034017
    deploy-param: opensearchDbaasAdapter
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/docker-elastic-curator
    location: v.6.8.23-0.25
    docker-image-id: timestamp
    deploy-param: opensearchCurator
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/docker-elastic-curator
    location: v.6.8.23-0.25
    prefix: elasticsearch_indices_cleaner
    docker-image-id: timestamp
    deploy-param: opensearchIndicesCleaner
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.Streaming/deployment-status-provisioner
    location: v.0.0.5
    docker-image-id: timestamp
    deploy-param: deploymentStatusProvisioner

  - type: image
    docker-image: artifactorycn.netcracker.com:17064/opensearchproject/opensearch-dashboards:1.2.0
    deploy-param: dockerDashboards
  - type: image
    docker-image: artifactorycn.netcracker.com:17064/library/busybox:1.35.0
    deploy-param: busybox
  - type: image
    docker-image: artifactorycn.netcracker.com:17064/bitnami/kubectl:1.23.3-debian-10-r6
    deploy-param: kubectl

  - type: scripts
    repo: PROD.Platform.ElasticStack/opensearch-service
    location: v.0.0.2
    alias: timestamp
    zip-name: migration-artifacts.zip
    name: migration-artifacts
    pre-deploy-entry-point: migration-artifacts/migration-artifacts.sh