integration:
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/opensearch-service
    location: v.0.0.9
    docker-image-id: timestamp
    deploy-param: opensearchOperator
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.Streaming/disaster-recovery-daemon
    location: 0.0.5
    docker-image-id: timestamp
    deploy-param: disasterRecoveryImage
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/opensearch-service
    location: v.0.0.9
    prefix: integration-tests
    docker-image-id: timestamp
    deploy-param: opensearchIntegrationTests
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/docker-opensearch
    location: 0.0.3
    docker-image-id: timestamp
    deploy-param: dockerOpensearch
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/elasticsearch-telegraf
    location: v.6.8.23-1.11
    docker-image-id: timestamp
    deploy-param: opensearchMonitoring
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/dbaas-opensearch-adapter
    location: 0.0.4
    docker-image-id: timestamp
    deploy-param: opensearchDbaasAdapter
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/dbaas_elasticsearch
    location: 1.0.22
    docker-image-id: timestamp
    deploy-param: elasticsearchDbaasAdapterImage
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/docker-elastic-curator
    location: v.6.8.23-0.28
    docker-image-id: timestamp
    deploy-param: opensearchCurator
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/docker-elastic-curator
    location: v.6.8.23-0.28
    prefix: elasticsearch_indices_cleaner
    docker-image-id: timestamp
    deploy-param: opensearchIndicesCleaner
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.Streaming/deployment-status-provisioner
    location: v.0.0.7
    docker-image-id: timestamp
    deploy-param: deploymentStatusProvisioner

  - type: image
    docker-image: artifactorycn.netcracker.com:17064/opensearchproject/opensearch-dashboards:1.2.0
    deploy-param: dockerDashboards
  - type: image
    docker-image: artifactorycn.netcracker.com:17064/library/busybox:1.35.0
    deploy-param: busybox
  - type: image
    docker-image: artifactorycn.netcracker.com:17064/bitnami/kubectl:1.23.3-debian-10-r6
    deploy-param: kubectl

  - type: scripts
    repo: PROD.Platform.ElasticStack/opensearch-service
    location: v.0.0.9
    alias: timestamp
    zip-name: migration-artifacts.zip
    name: migration-artifacts
    pre-deploy-entry-point: migration-artifacts/migration-artifacts.sh
