build:
  env:
    type: application-integration
    version: openshift-dd-2
  networkRules: integration
  integration:
    multi_image_descriptor: true
    dmp_descriptor:
      version: '1.12'

publication:
  application-manifest:
    am-mf: application.mf
    am-zip: application.zip

deployment:
  availability_check: true
  availability:
    resource: Job
    conditions: Successful
    interval: 30
    max_tries: 60
    delay: 60
  mode: reinstall
  values:
    dashboards:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - host: dashboards-opensearch-service-v2.ci-master.openshift.sdntest.netcracker.com
            paths:
              - path: /

    opensearch:
      securityConfig:
        enabled: true
        path: "/usr/share/opensearch/config/opensearch-security"
        authc:
          basic:
            username: "netcrk"
            password: "crknet"
          oidc:
            openid_connect_url: "http://idp.framework-ci-services:8080/.well-known/openid-configuration"
      master:
        enabled: true
        replicas: 3
        persistence:
          enabled: true
          storageClass: "local-path"
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 2Gi
        javaOpts: "-Xms1024m -Xmx1024m"
      client:
        ingress:
          enabled: true
          path: /
          hosts:
            - opensearch-opensearch-service-v2.ci-master.openshift.sdntest.netcracker.com
      snapshots:
        enabled: true
        repositoryName: "snapshots"
        persistentVolume: "pv-opensearch-snapshots"
        persistentVolumeClaim: "pvc-opensearch-snapshots"
        size: 2Gi

    monitoring:
      enabled: true
      includeIndices: true
      slowQueries:
        enabled: true
      resources:
        requests:
          memory: 256Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 200m

    dbaasAdapter:
      enabled: true
      dbaasUsername: "dbaas-aggregator"
      dbaasPassword: "dbaas-aggregator"
      registrationAuthUsername: "cluster-dba"
      registrationAuthPassword: "Bnmq5567_PO"
      opensearchRepo: "snapshots"
      opensearchRepoRoot: "/usr/share/opensearch"
      apiVersion: v2
      resources:
        requests:
          memory: 32Mi
          cpu: 50m
        limits:
          memory: 32Mi
          cpu: 200m
      securityContext:
        runAsUser: 1000

    curator:
      enabled: true
      snapshotRepositoryName: "snapshots"
      username: "admin"
      password: "admin"
      resources:
        requests:
          memory: 256Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 200m
      securityContext:
        runAsUser: 1000
        fsGroup: 1000

cloud:
  type: helm
  url: https://ci-master.openshift.sdntest.netcracker.com:6443
  project: opensearch-service-v2

integration:
  - type: find-latest-deployment-descriptor
    repo: PROD.Platform.ElasticStack/opensearch-service
    location: master
    docker-image-id: timestamp
    deploy-param: opensearchTransferCharts
  - type: image
    docker-image: artifactorycn.netcracker.com:17152/netcracker/qubership-opensearch-operator:main
    deploy-param: opensearchServiceOperator
    service-name: opensearch-service-operator
  - type: image
    docker-image: artifactorycn.netcracker.com:17152/netcracker/disaster-recovery-daemon:main
    deploy-param: disasterRecoveryImage
    service-name: disaster-recovery-daemon
  - type: image
    docker-image: artifactorycn.netcracker.com:17152/netcracker/qubership-opensearch-integration-tests:main
    deploy-param: opensearchIntegrationTests
    service-name: opensearch-integration-tests
  - type: image
    docker-image: artifactorycn.netcracker.com:17152/netcracker/qubership-docker-opensearch:main
    deploy-param: dockerOpensearch
    service-name: docker-opensearch
  - type: image
    docker-image: artifactorycn.netcracker.com:17152/netcracker/qubership-opensearch-tls-init:main
    deploy-param: opensearchTlsInit
    service-name: opensearch-tls-init
  - type: image
    docker-image: artifactorycn.netcracker.com:17152/netcracker/qubership-opensearch-monitoring:main
    deploy-param: opensearchMonitoring
    service-name: opensearch-monitoring
  - type: image
    docker-image: artifactorycn.netcracker.com:17152/netcracker/qubership-opensearch-dbaas-adapter:main
    deploy-param: opensearchDbaasAdapter
    service-name: dbaas-opensearch-adapter
  - type: image
    docker-image: artifactorycn.netcracker.com:17152/netcracker/qubership-opensearch-curator:main
    deploy-param: opensearchCurator
    service-name: docker-elastic-curator
  - type: image
    docker-image: artifactorycn.netcracker.com:17152/netcracker/qubership-opensearch-indices-cleaner:main
    deploy-param: opensearchIndicesCleaner
    service-name: opensearch-indices-cleaner
  - type: image
    docker-image: artifactorycn.netcracker.com:17152/netcracker/qubership-deployment-status-provisioner:main
    deploy-param: deploymentStatusProvisioner
    service-name: deployment-status-provisioner
  - type: image
    docker-image: artifactorycn.netcracker.com:17064/opensearchproject/opensearch-dashboards:2.11.1
    deploy-param: dockerDashboards
  - type: image
    docker-image: artifactorycn.netcracker.com:17064/library/busybox:1.35.0
    deploy-param: busybox
  - type: image
    docker-image: artifactorycn.netcracker.com:17014/product/prod.platform.streaming_docker-kubectl:0.0.2_20230324-083045
    deploy-param: kubectl
  - type: scripts
    repo: PROD.Platform.ElasticStack/opensearch-service
    location: master
    alias: timestamp
    zip-name: migration-artifacts.zip
    name: migration-artifacts
    pre-deploy-entry-point: migration-artifacts/migration-artifacts.sh
  - type: scripts
    repo: PROD.Platform.ElasticStack/deployment-utils
    location: master
    alias: timestamp
    zip-name: devops-scripts.zip
    name: crd-upgrade
    pre-deploy-entry-point: crd-upgrade.sh
  - type: scripts
    repo: PROD.Platform.ElasticStack/deployment-utils
    location: master
    alias: latest
    zip-name: devops-scripts.zip
    name: privileged-pss
    pre-deploy-entry-point: privileged-pss.sh
