{{- if .Values.integrationTests.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "opensearch.fullname" . }}-integration-tests
spec:
  selector:
    matchLabels:
      name: {{ template "opensearch.fullname" . }}-integration-tests
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
{{- with .Values.global.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{- with .Values.integrationTests.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
        name: {{ template "opensearch.fullname" . }}-integration-tests
    spec:
      serviceAccountName: {{ template "opensearch.fullname" . }}-integration-tests
      {{- if .Values.integrationTests.affinity }}
      affinity:
      {{ .Values.integrationTests.affinity | toJson }}
      {{- end }}
      containers:
        - name: {{ template "opensearch.fullname" . }}-integration-tests
          image: {{ template "integration-tests.image" . }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: OPENSEARCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TAGS
              value: {{ .Values.integrationTests.tags }}
            - name: OPENSEARCH_HOST
              value: {{ template "opensearch.fullname" . }}
            - name: OPENSEARCH_PORT
              value: "{{ .Values.integrationTests.opensearchPort | default 9200 }}"
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ template "opensearch.fullname" . }}-secret
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "opensearch.fullname" . }}-secret
            - name: OPENSEARCH_MASTER_NODES_NAME
              value: {{ template "master-nodes" . }}
            - name: IDENTITY_PROVIDER_URL
              value: "{{ .Values.integrationTests.identityProviderUrl }}"
            - name: IDENTITY_PROVIDER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-integration-tests-secret
                  key: idp-registration-token
            - name: IDENTITY_PROVIDER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-integration-tests-secret
                  key: idp-username
            - name: IDENTITY_PROVIDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-integration-tests-secret
                  key: idp-password
            - name: PROMETHEUS_URL
              value: "{{ .Values.integrationTests.prometheusUrl }}"
            {{- if .Values.dbaasAdapter.enabled }}
            - name: OPENSEARCH_DBAAS_ADAPTER_HOST
              value: {{ template "dbaas-adapter.name" . }}
            - name: OPENSEARCH_DBAAS_ADAPTER_PORT
              value: "{{ .Values.integrationTests.opensearchDbaasAdapterPort | default 8080 }}"
            - name: OPENSEARCH_DBAAS_ADAPTER_REPOSITORY
              value: {{ .Values.dbaasAdapter.opensearchRepo | default "snapshots" }}
            - name: OPENSEARCH_DBAAS_ADAPTER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ template "dbaas-adapter.name" . }}-secret
            - name: OPENSEARCH_DBAAS_ADAPTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "dbaas-adapter.name" . }}-secret
            {{- end }}
            {{- if .Values.curator.enabled }}
            - name: OPENSEARCH_CURATOR_HOST
              value: {{ template "opensearch.fullname" . }}-curator
            - name: OPENSEARCH_CURATOR_PORT
              value: "{{ .Values.integrationTests.opensearchCuratorPort | default 8080 }}"
            - name: OPENSEARCH_CURATOR_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ template "opensearch.fullname" . }}-curator-secret
            - name: OPENSEARCH_CURATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "opensearch.fullname" . }}-curator-secret
            {{- if .Values.integrationTests.statusWritingEnabled }}
            - name: STATUS_CUSTOM_RESOURCE_GROUP
              value: apps
            - name: STATUS_CUSTOM_RESOURCE_VERSION
              value: v1
            - name: STATUS_CUSTOM_RESOURCE_PLURAL
              value: deployments
            - name: STATUS_CUSTOM_RESOURCE_NAME
              value: {{ printf "%s-integration-tests" (include "opensearch.fullname" .) }}
            - name: STATUS_CUSTOM_RESOURCE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STATUS_WRITING_ENABLED
              value: "{{ .Values.integrationTests.statusWritingEnabled }}"
            - name: ONLY_INTEGRATION_TESTS
              value: "false"
            - name: IS_SHORT_STATUS_MESSAGE
              value: "{{ .Values.integrationTests.isShortStatusMessage }}"
            {{- end }}
            {{- end }}
          resources:
            requests:
              memory: {{ default "256Mi" .Values.integrationTests.resources.requests.memory }}
              cpu: {{ default "200m" .Values.integrationTests.resources.requests.cpu }}
            limits:
              memory: {{ default "256Mi" .Values.integrationTests.resources.limits.memory }}
              cpu: {{ default "400m" .Values.integrationTests.resources.limits.cpu }}
          volumeMounts:
            - name: output
              mountPath: /opt/robot/output
          terminationMessagePath: /dev/termination-log
      volumes:
        - name: output
          emptyDir: {}
  {{- end }}
