{{- if .Values.integrationTests.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opensearch.fullname" . }}-integration-tests-secret
type: Opaque
stringData:
  idp-registration-token: "{{ .Values.integrationTests.secrets.idp.registrationToken }}"
  idp-username: "{{ .Values.integrationTests.secrets.idp.username }}"
  idp-password: "{{ .Values.integrationTests.secrets.idp.password }}"
  prometheus-user: "{{ .Values.integrationTests.secrets.prometheus.user }}"
  prometheus-password: "{{ .Values.integrationTests.secrets.prometheus.password }}"
{{- end }}