## Append samples you want in your CSV to this file as resources ##
resources:
- netcracker.com_v1_opensearchservice.yaml
- _v1_opensearchservice.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
