# permissions for end users to view opensearchservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchservice-viewer-role
rules:
- apiGroups:
  - netcracker.com
  resources:
  - opensearchservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netcracker.com
  resources:
  - opensearchservices/status
  verbs:
  - get
