{{- if (eq (include "monitoring.enabled" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
  name: {{ template "opensearch.fullname" . }}-monitoring
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods/exec
      - services
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
{{- end }}