{{- if (eq (include "monitoring.enabled" .) "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opensearch.fullname" . }}-monitoring
  namespace: {{ .Release.Namespace }}
{{- end }}