{{- if (and (eq (include "monitoring.enabled" .) "true") (ne .Values.monitoring.monitoringType "influxdb")) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "opensearch.fullname" . }}-service-monitor
  labels:
    {{- include "opensearch-service.coreLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-service-monitor
    app.kubernetes.io/component: monitoring
spec:
  endpoints:
    - interval: {{ .Values.monitoring.serviceMonitor.clusterStateScrapeInterval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.clusterStateScrapeTimeout }}
      port: prometheus-cli
      scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      component: opensearch-monitoring
      name: {{ template "opensearch.fullname" . }}-monitoring
{{- end }}