{{- if  not .Values.global.externalOpensearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    role: data
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
    name: {{ template "opensearch.fullname" . }}-data-svc
    app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-data-svc
  name: {{ template "opensearch.fullname" . }}-data-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 9300
      name: transport
    - port: 9200
      name: http
    - port: 9600
      name: metrics
    - port: 9650
      name: rca
  clusterIP: None
  selector:
  {{- if .Values.opensearch.data.dedicatedPod.enabled }}
    role: data
  {{- else }}
    role: master
  {{- end }}
{{- end }}
