{{- if not .Values.global.externalOpensearch.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "opensearch.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
{{- if .Values.global.psp.create }}
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
      - {{ template "opensearch.fullname" . }}-psp
{{- else }}
rules: []
{{- end }}
{{- end }}
