{{- if  not .Values.global.externalOpensearch.enabled }}
{{- if and .Values.opensearch.snapshots.enabled .Values.opensearch.snapshots.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opensearch.fullname" . }}-s3-secret
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  s3-key-id: "{{ .Values.opensearch.snapshots.s3.keyId }}"
  s3-key-secret: "{{ .Values.opensearch.snapshots.s3.keySecret }}"
{{- end }}
{{- end }}