{{ if and (not .Values.global.externalOpensearch.enabled) .Values.global.tls.generateCerts.enabled (ne (include "certProvider" .) "cert-manager") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "opensearch.fullname" . }}-tls-init
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: {{ template "opensearch.fullname" . }}-tls-init
      labels:
{{ include "opensearch.labels.standard" . | indent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "opensearch.fullname" . }}-tls-init
      securityContext:
        {{- include "opensearch-service.globalPodSecurityContext" . | nindent 8 }}
      containers:
        - name: tls-init
          image: {{ template "opensearch.image" . }}
          imagePullPolicy: "{{ .Values.opensearch.imagePullPolicy | default "Always" }}"
          env:
            - name: OPENSEARCH_FULLNAME
              value: {{ template "opensearch.fullname" . }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ADDITIONAL_DNS_NAMES
              value: "{{ join " " (include "opensearch.certDnsNames" . | fromYamlArray) }}"
            - name: ADDITIONAL_IP_ADDRESSES
              value: "{{ join " " (include "opensearch.certIpAddresses" . | fromYamlArray) }}"
            - name: DURATION_DAYS
              value: "{{ .Values.global.tls.generateCerts.durationDays | default 365 }}"
            - name: TRANSPORT_CERTIFICATES_SECRET_NAME
              value: {{ template "opensearch.transport-cert-secret-name" . }}
            - name: ADMIN_CERTIFICATES_SECRET_NAME
              value: {{ template "opensearch.admin-cert-secret-name" . }}
            {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
            - name: REST_CERTIFICATES_SECRET_NAME
              value: {{ template "opensearch.rest-cert-secret-name" . }}
            {{- end }}
          resources:
            requests:
              memory: {{ default "128Mi" .Values.opensearch.tlsInit.resources.requests.memory  }}
              cpu: {{ default "25m" .Values.opensearch.tlsInit.resources.requests.cpu  }}
            limits:
              memory: {{ default "128Mi" .Values.opensearch.tlsInit.resources.limits.memory  }}
              cpu: {{ default "100m" .Values.opensearch.tlsInit.resources.limits.cpu  }}
          command:
            - "/bin/sh"
            - "-ec"
            - "bin/generate-certificates.sh"
          securityContext:
            {{- include "opensearch-service.globalContainerSecurityContext" . | nindent 12 }}
{{- end }}
