{{ if and .Values.global.rbac.enabled (not .Values.global.externalOpensearch.enabled) .Values.global.tls.generateCerts.enabled (ne (include "certProvider" .) "cert-manager") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "opensearch.fullname" . }}-tls-init
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - create
      - get
      - update
{{- if .Values.global.psp.create }}
  - apiGroups: ["policy"]
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ template "opensearch.fullname" . }}-psp
{{- end }}
{{- end }}
