{{ if eq (include "tlsInitJob.enabled" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "opensearch.fullname" . }}-tls-init
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - patch
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
{{- end }}
