{{- if .Values.elasticsearchDbaasAdapter.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    name: {{ .Values.elasticsearchDbaasAdapter.name }}
    component: dbaas-elasticsearch-adapter
  name: {{ .Values.elasticsearchDbaasAdapter.name }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    name: {{ .Values.elasticsearchDbaasAdapter.name }}
    component: dbaas-elasticsearch-adapter
{{- end }}