kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "opensearch.fullname" . }}-get-opensearch-ver
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "-180"
subjects:
  - kind: ServiceAccount
    name: {{ template "opensearch.fullname" . }}-get-opensearch-ver
roleRef:
  kind: Role
  name: {{ template "opensearch.fullname" . }}-get-opensearch-ver
  apiGroup: rbac.authorization.k8s.io
