{{- $secretName := include "opensearch.admin-cert-secret-name" . }}
{{- $install := and (eq (include "opensearch.tlsEnabled" .) "true") .Values.global.tls.enabled (eq (include "opensearch.adminCertificatesSpecified" .) "true") }}
{{- if and $install (ne (include "certProvider" .) "cert-manager") }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
data:
{{- if not .Values.global.tls.generateCerts.enabled }}
  {{- if .Values.opensearch.tls.admin.certificates.crt }}
  tls.crt: {{ .Values.opensearch.tls.admin.certificates.crt | quote }}
  {{- end }}
  {{- if .Values.opensearch.tls.admin.certificates.key }}
  tls.key: {{ .Values.opensearch.tls.admin.certificates.key | quote }}
  {{- end }}
  {{- if .Values.opensearch.tls.admin.certificates.ca }}
  ca.crt: {{ .Values.opensearch.tls.admin.certificates.ca | quote }}
  {{- end }}
{{- end }}
{{- end }}