{{- if not .Values.global.externalOpensearch.enabled }}
{{- if and (eq (include "opensearch.ingressEnabled" .) "true") .Values.opensearch.client.enabled }}
{{- $fullName := printf "%s" (include "opensearch.fullname" .) }}
{{- $ingressPath := .Values.opensearch.client.ingress.path }}
kind: Ingress
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
metadata:
  name: {{ $fullName }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
  annotations:
    {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-verify: 'on'
    nginx.ingress.kubernetes.io/proxy-ssl-name: '{{ template "opensearch.fullname" . }}-internal.{{ .Release.Namespace }}'
    nginx.ingress.kubernetes.io/proxy-ssl-secret: '{{ .Release.Namespace }}/{{ template "opensearch.rest-cert-secret-name" . }}'
    {{- end }}
    {{- if and .Values.opensearch.client.ingress.className (not (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress")) }}
    kubernetes.io/ingress.class: {{ .Values.opensearch.client.ingress.className }}
    {{- end }}
    {{- with .Values.opensearch.client.ingress.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.opensearch.client.ingress.className (.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") }}
  ingressClassName: {{ .Values.opensearch.client.ingress.className }}
  {{- end }}
  rules:
  {{- range (include "opensearch.ingressHost" . | fromYamlArray) }}
    - host: {{ . | quote }}
      http:
        paths:
          - {{- if (not ($.Capabilities.APIVersions.Has "route.openshift.io/v1/Route")) }}
            path: {{ $ingressPath }}
            {{- end }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-internal
                port:
                  number: 9200
            {{- else }}
            backend:
              {{/* Currently ingress is not a business access point for OpenSearch and used only for debugging. Need to be use defaul client service if external access became business case for OpenSearch. */}}
              serviceName: {{ $fullName }}-internal
              servicePort: 9200
            {{- end }}
  {{- end }}
{{- end }}
{{- end }}
