{{- if  not .Values.global.externalOpensearch.enabled }}
{{- if and .Values.opensearch.client.ingress.enabled .Values.opensearch.client.enabled }}
{{- $fullName := printf "%s" (include "opensearch.fullname" .) }}
{{- $ingressPath := .Values.opensearch.client.ingress.path }}
kind: Ingress
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
metadata:
  name: {{ $fullName }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{- with .Values.opensearch.client.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.opensearch.client.ingress.tls }}
  tls:
  {{- range .Values.opensearch.client.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.opensearch.client.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 9200
            {{- else }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 9200
            {{- end }}
  {{- end }}
{{- end }}
{{- end }}
