{{- if not .Values.global.externalOpensearch.enabled }}
{{- if and .Values.opensearch.client.enabled .Values.opensearch.client.dedicatedPod.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    role: client
  name: {{ template "opensearch.fullname" . }}-client
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.opensearch.client.replicas }}
  selector:
    matchLabels:
{{ include "opensearch.labels.selector" . | indent 6 }}
      role: client
  template:
    metadata:
      labels:
{{- with .Values.global.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{- with .Values.opensearch.client.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{ include "opensearch.labels.standard" . | indent 8 }}
        role: client
      annotations:
        "opensearch/config-checksum": {{ include (print $.Template.BasePath "/opensearch/config-secret.yaml") . | sha256sum }}
{{- if .Values.opensearch.client.podAnnotations }}
{{ toYaml .Values.opensearch.client.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.opensearch.client.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.opensearch.client.imagePullSecrets | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "opensearch.serviceAccountName" . }}
    {{- with .Values.opensearch.client.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.opensearch.client.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.opensearch.client.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
      securityContext:
        {{- include "opensearch-service.globalPodSecurityContext" . | nindent 8 }}
        {{- with .Values.opensearch.securityContextCustom }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}
      initContainers:
{{- if .Values.opensearch.sysctl.enabled }}
        - name: init-sysctl
          image: {{ template "busybox.image" . }}
          command:
            - sysctl
            - -w
            - vm.max_map_count={{ .Values.opensearch.maxMapCount }}
          securityContext:
            privileged: true
            runAsNonRoot: false
            runAsUser: 0
{{- end }}
{{- if .Values.opensearch.extraInitContainers }}
{{ toYaml .Values.opensearch.extraInitContainers| indent 8 }}
{{- end }}
      containers:
        - name: opensearch
          env:
            - name: cluster.name
              value: {{ .Values.global.clusterName }}
            - name: node.roles
              value: "ingest,remote_cluster_client"
            - name: network.host
              value: "0.0.0.0"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: {{ template "opensearch.fullname" . }}-discovery
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: TLS_ENABLED
              value: "{{ include "opensearch.tlsEnabled" . }}"
            - name: OPENSEARCH_JAVA_OPTS
              value: {{ .Values.opensearch.client.javaOpts }}
            - name: DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI
              value: "{{ not .Values.opensearch.performanceAnalyzerEnabled }}"
{{- if .Values.opensearch.extraEnvs }}
{{ toYaml .Values.opensearch.extraEnvs | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.opensearch.client.resources | indent 12 }}
          securityContext:
            {{- include "opensearch-service.globalContainerSecurityContext" . | nindent 12 }}
          image: {{ template "opensearch.image" . }}
          imagePullPolicy: {{ .Values.opensearch.imagePullPolicy | default "Always" | quote }}
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
            - containerPort: 9600
              name: metrics
            - containerPort: 9650
              name: rca
          readinessProbe:
        {{- if .Values.opensearch.client.readinessProbe }}
{{ toYaml .Values.opensearch.client.readinessProbe | indent 12 }}
        {{- else }}
            tcpSocket:
              port: transport
            initialDelaySeconds: 60
            periodSeconds: 10
        {{- end }}
    {{- with .Values.opensearch.client.livenessProbe}}
          livenessProbe:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.opensearch.client.startupProbe}}
          startupProbe:
{{ toYaml . | indent 12 }}
    {{- end }}
          volumeMounts:
        {{- if .Values.opensearch.config }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/opensearch.yml
              name: config
              subPath: opensearch.yml
        {{- end }}
        {{- if .Values.opensearch.log4jConfig }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/log4j2.properties
              name: config
              subPath: log4j2.properties
        {{- end }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/logging.yml
              name: config
              subPath: logging.yml
            - mountPath: {{ .Values.opensearch.configDirectory }}/jvm.options
              name: config
              subPath: jvm.options
            - mountPath: {{ .Values.opensearch.configDirectory }}/transport-crt.pem
              name: transport-certs
              subPath: {{ template "opensearch.transport-cert-path" . }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/transport-key.pem
              name: transport-certs
              subPath: {{ template "opensearch.transport-key-path" . }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/transport-root-ca.pem
              name: transport-certs
              subPath: {{ template "opensearch.transport-root-ca-path" . }}
            {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/rest-crt.pem
              name: rest-certs
              subPath: {{ template "opensearch.rest-cert-path" . }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/rest-key.pem
              name: rest-certs
              subPath: {{ template "opensearch.rest-key-path" . }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/rest-root-ca.pem
              name: rest-certs
              subPath: {{ template "opensearch.rest-root-ca-path" . }}
            {{- end }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/admin-crt.pem
              name: admin-certs
              subPath: {{ template "opensearch.admin-cert-path" . }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/admin-key.pem
              name: admin-certs
              subPath: {{ template "opensearch.admin-key-path" . }}
            - mountPath: {{ .Values.opensearch.configDirectory }}/admin-root-ca.pem
              name: admin-certs
              subPath: {{ template "opensearch.admin-root-ca-path" . }}
{{- if .Values.opensearch.extraVolumeMounts }}
{{ toYaml .Values.opensearch.extraVolumeMounts | indent 12 }}
{{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ template "opensearch.fullname" . }}-config
        - name: transport-certs
          secret:
            secretName: {{ template "opensearch.transport-cert-secret-name" . }}
        {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
        - name: rest-certs
          secret:
            secretName: {{ template "opensearch.rest-cert-secret-name" . }}
        {{- end }}
        - name: admin-certs
          secret:
            secretName: {{ template "opensearch.admin-cert-secret-name" . }}
{{- if .Values.opensearch.extraVolumes }}
{{ toYaml .Values.opensearch.extraVolumes | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
