apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opensearch.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.opensearch.config }}
  opensearch.yml: {{ toYaml .Values.opensearch.config | b64enc | quote }}
  {{- end }}
  {{- if .Values.opensearch.log4jConfig }}
  log4j2.properties: {{ .Values.opensearch.log4jConfig | b64enc | quote }}
  {{- end }}
  logging.yml: {{ toYaml .Values.opensearch.loggingConfig | b64enc | quote }}
