{{- if  not .Values.global.externalOpensearch.enabled }}
kind: Service
apiVersion: v1
metadata:
  annotations:
{{ toYaml .Values.opensearch.client.service.annotations | indent 4 }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    role: client
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
    name: {{ template "opensearch.fullname" . }}-internal
    app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-internal
  name: {{ template "opensearch.fullname" . }}-internal
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 9200
  selector:
  {{- if .Values.opensearch.client.dedicatedPod.enabled }}
    role: client
  {{- else }}
    role: master
  {{- end }}
  type: {{ .Values.opensearch.client.service.type }}
{{- end }}
