{{- if and .Values.global.tls.generateCerts.enabled .Values.opensearch.tls.generateCerts.enabled (eq (include "certProvider" .) "cert-manager") (not (.Values.global.tls.generateCerts.clusterIssuerName)) (not .Values.global.externalOpensearch.enabled) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "opensearch.fullname" . }}-tls-issuer
  namespace: {{ .Release.Namespace }}
  label:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ template "opensearch.fullname" . }}-ca-cert
{{- end }}