{{- if .Values.opensearch.master.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    role: master
  name: {{ template "opensearch.fullname" . }}-discovery
  namespace: {{ .Release.Namespace }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 9300
      protocol: TCP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    role: master
{{- end }}
