{{- $secretName := include "opensearch.rest-cert-secret-name" . }}
{{- if and (eq (include "opensearch.tlsEnabled" .) "true") .Values.global.tls.enabled (not .Values.opensearch.tls.rest.existingCertSecret) (eq (include "opensearch.restCertificatesSpecified" .) "true") }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.opensearch.tls.rest.certificates.crt | quote }}
  tls.key: {{ .Values.opensearch.tls.rest.certificates.key | quote }}
  ca.crt: {{ .Values.opensearch.tls.rest.certificates.ca | quote }}
{{- end }}