{{- if  not .Values.global.externalOpensearch.enabled }}
{{- if .Values.global.rbac.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
  name: {{ template "opensearch.fullname" . }}-rolebinding
roleRef:
  kind: Role
  name: {{ template "opensearch.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "opensearch.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
