# This secret is used for changing OpenSearch credentials. It is created by Helm, but all updates are performed by operator.
# If `opensearch-secret` secret exists, data is taken from it, otherwise, from `.Values` parameters.
{{- $secretName := printf "%s-secret-old" (include "opensearch.fullname" .) }}
{{- if not (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" (include "opensearch.fullname" .))) | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/resource-policy": keep
type: Opaque
{{- if $secretObj }}
data: {{ get $secretObj "data" | toYaml | nindent 2 }}
{{- else }}
stringData:
  {{- if .Values.global.externalOpensearch.enabled }}
      username: "{{ .Values.global.externalOpensearch.username }}"
      password: "{{ .Values.global.externalOpensearch.password }}"
  {{- else }}
      username: "{{ (include "opensearch.username" .) }}"
      password: "{{ (include "opensearch.password" .) }}"
  {{- end }}
{{- end }}
{{- end }}
