{{- if not (and .Values.opensearch.securityConfig.authc.basic.username .Values.opensearch.securityConfig.authc.basic.password) }}
{{ fail "credentials for OpenSearch ('.Values.opensearch.securityConfig.authc.basic.username' and '.Values.opensearch.securityConfig.authc.basic.password') must be specified" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opensearch.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
type: Opaque
stringData:
  username: "{{ .Values.opensearch.securityConfig.authc.basic.username }}"
  password: "{{ .Values.opensearch.securityConfig.authc.basic.password }}"
