{{- if  not .Values.global.externalOpensearch.enabled }}
{{ if .Values.opensearch.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opensearch.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ end }}
{{- end }}
