{{- $install := and (not .Values.global.externalOpensearch.enabled) .Values.global.tls.generateCerts.enabled .Values.opensearch.tls.generateCerts.enabled }}
{{- if and $install (eq (include "certProvider" .) "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "opensearch.fullname" . }}-tls-transport-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
spec:
  secretName: {{ template "opensearch.transport-cert-secret-name" . }}
  duration: {{ default 365 .Values.global.tls.generateCerts.durationDays | mul 24 }}h0m0s
  commonName: opensearch-node
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  subject:
    countries:
      - CA
    organizations:
      - Opensearch
    organizationalUnits:
      - Opensearch
    localities:
      - Opensearch
  dnsNames: {{ include "opensearch.certDnsNames" . | nindent 4 }}
  ipAddresses: {{ include "opensearch.certIpAddresses" . | nindent 4 }}
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - data encipherment
  issuerRef:
  {{- if .Values.global.tls.generateCerts.clusterIssuerName }}
    name: {{ .Values.global.tls.generateCerts.clusterIssuerName }}
    kind: ClusterIssuer
  {{- else }}
    name: {{ template "opensearch.fullname" . }}-tls-issuer
    kind: Issuer
  {{- end }}
    group: cert-manager.io
{{- end }}