{{- $secretName := include "opensearch.transport-cert-secret-name" . }}
{{- $install := and (eq (include "opensearch.tlsEnabled" .) "true") .Values.global.tls.enabled (not .Values.opensearch.tls.transport.existingCertSecret) (eq (include "opensearch.transportCertificatesSpecified" .) "true") }}
{{- if and $install (ne (include "certProvider" .) "cert-manager") (not .Values.global.tls.generateCerts.enabled) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.opensearch.tls.transport.certificates.crt | quote }}
  tls.key: {{ .Values.opensearch.tls.transport.certificates.key | quote }}
  ca.crt: {{ .Values.opensearch.tls.transport.certificates.ca | quote }}
{{- end }}