{{- if not .Values.global.externalOpensearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opensearch.fullname" . }}-trusted-certs
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
type: Opaque
{{- end }}
