{{- if eq (include "opensearch-status-provisioner.cleanupEnabled" .) "true" }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
roleRef:
  kind: Role
  name: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
  apiGroup: rbac.authorization.k8s.io
{{- end }}