{{- if eq (include "opensearch-status-provisioner.cleanupEnabled" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}