{{- if .Values.statusProvisioner.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "opensearch.fullname" . }}-status-provisioner
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "opensearch.fullname" . }}-status-provisioner
roleRef:
  kind: Role
  name: {{ template "opensearch.fullname" . }}-status-provisioner
  apiGroup: rbac.authorization.k8s.io
{{- end }}