{{- if .Values.statusProvisioner.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opensearch.fullname" . }}-status-provisioner
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
{{- end }}