{{ if and .Values.ENABLE_PRIVILEGED_PSS (eq (include "opensearch.restrictedEnvironment" .) "false") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opensearch.fullname" . }}-update-resources
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range . }}
  - name: {{ .name }}
{{- end }}
{{- end }}
{{ end }}