{{- if and .Values.curator.enabled (or (not .Values.opensearch.snapshots.enabled) .Values.opensearch.snapshots.s3.enabled) (not .Values.curator.storage.persistentVolumeClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ template "opensearch.fullname" . }}-curator
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.curator.storage.size | default "1Gi" }}
  storageClassName: "{{ include "curator.storage.storageClassName" .}}"
{{- end }}
