{{- if .Values.curator.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ template "opensearch.fullname" . }}-curator
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.curator.storage.size | default "1Gi" }}
  {{- if .Values.curator.storage.persistentVolume }}
  volumeName: {{ .Values.curator.storage.persistentVolume }}
  {{- end }}
  storageClassName: "{{ include "curator.storage.storageClassName" .}}"
{{- end }}
