{{- if .Values.curator.enabled }}
{{- $s3Data := fromYaml (include "backupDaemon.s3Aliases" .) }}
{{- if $s3Data.items }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
    component: opensearch-curator
    name: {{ template "opensearch.fullname" . }}-curator
    app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-curator
    app.kubernetes.io/instance: {{ cat (printf "%s-curator"  (include "opensearch.fullname" .)) .Values.DELIMITER .Release.Namespace | nospace | trunc 63 }}
    app.kubernetes.io/technology: python
  name: {{ template "opensearch.fullname" . }}-s3-aliases
type: Opaque
stringData:
  s3_aliases.json: |
{{ include "backupDaemon.s3AliasesJson" . | indent 4 }}
{{- end }}
{{- end }}
