name: Branch Deleted
on: delete

env:
  TAG_NAME: ${{ github.event.ref }}

jobs:
  delete:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-opensearch-integration-tests
            file: integration-tests/docker/Dockerfile
            context: integration-tests
          - name: qubership-opensearch-tls-init
            file: tls-init/docker/Dockerfile
            context: tls-init
          - name: qubership-opensearch-operator
            file: operator/Dockerfile
            context: operator
          - name: qubership-opensearch-transfer
            file: docker-transfer/Dockerfile
            context: ""
          - name: qubership-opensearch-monitoring
            file: monitoring/docker/Dockerfile
            context: monitoring
          - name: qubership-opensearch-curator
            file: curator/docker/backup-docker/Dockerfile
            context: curator
          - name: qubership-opensearch-indices-cleaner
            file: curator/opensearch_indices_cleaner/docker/Dockerfile
            context: curator/opensearch_indices_cleaner
          - name: qubership-opensearch-dbaas-adapter
            file: dbaas-adapter/docker/Dockerfile
            context: dbaas-adapter
          - name: qubership-docker-opensearch-2
            file: docker-opensearch/2x/docker/Dockerfile
            context: docker-opensearch
          - name: qubership-docker-opensearch-3
            file: docker-opensearch/3x/docker/Dockerfile
            context: docker-opensearch
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Get package IDs for delete
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@v0.0.1
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ env.TAG_NAME }}
          access-token: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.component.name }}
          package-type: 'container'
          package-version-ids: ${{ steps.get-ids-for-delete.outputs.ids-for-delete }}
        if: ${{ steps.get-ids-for-delete.outputs.ids-for-delete != '' }}
