name: Run Opensearch Pipeline

permissions:
  contents: read

on:
  # pull_request:
  #   types: [opened, synchronize, reopened]
  #   branches: [main]
  push

jobs:
  Wait-for-images:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.wait.outputs.conclusion }}
    steps:
      - name: Wait for dev_build.yml to complete
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@3e428f45132119ce49d90f3770a45d4fe1d1078d  #v2.0.4
        id: wait
        with:
          workflow: dev_build.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          poll-interval: 20
  Opensearch-Pipeline:
    needs: Wait-for-images
    uses: Netcracker/qubership-test-pipelines/.github/workflows/opensearch.yaml@fix_linting_errors_v2 #v1.5.2
    with:
      service_branch: '${{ github.head_ref || github.ref_name }}'
      pipeline_branch: 'fix_linting_errors_v2' #this value must match the value after '@' in 'uses'
      runner_type: 'ubuntu-latest'
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
